### PR TITLE
Voron0.1_CR10_E3_Mini_Afterburner

### PR DESCRIPTION
**Pull request by CGrassin**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

printer_mods/CGrassin/V0.1_CR10_E3_Mini_Afterburner : a new Cowling part to fit an Ender 3/CR10 hotend (very very inexpensive despite a lower maximum flow capability than other options).

#### How was it tested? 

Currently being used on my v0.1 (about 36h of printing with this mod).

#### Any background context you want to provide?

No.

#### Further notes

This part does require a bit of support material (please read the readme). This is due to the tight fit in the Mini Afterburner assembly, I see no way around this.
I was asked on the Discord to submit this mod.
Originally posted here : https://www.prusaprinters.org/prints/131985-voron-v01-cr10-hotend-mini-afterburner-mod

### CODE REVIEW

**Comment by VinnyCordeiro** [comment]
> This part does require a bit of support material (please read the readme). This is due to the tight fit in the Mini Afterburner assembly, I see no way around this.

You have to add the support yourself on the feature that requires it, so anyone that want to print this mod does not have to be worried about that. That's on the rules, and I'm afraid that the mod won't be approved because of that.

**Comment by CGrassin** [comment]
I agree with this comment. I added some manually generated support material in CAD that mimics Cura's default support settings which I was using.

Screenshots:
Left: Built-in support, Right: no support
_Left: Built-in support, Right: default_

layer view
_View of the support structure that is designed in the model_

However:
1. I have **not** printed the file with built-in support since I don't currently have access to a 3D printer and won't for several months. When sliced with Cura with Voron's settings, the file behaves as expected, but I technically don't have proof that it does print correctly. Therefore, I have unchecked the corresponding checkbox. This may or may not mean that this PR is on hold.
2. I wanted to include both the version with built-in support and without support (both STL and STEP files). However, I don't know if the current file naming/documentation is clear enough about this. Feedback would be appreciated.

Thanks!

**Comment by MapleLeafMakers** [comment]
@CGrassin this PR will need to be updated to resolve merge conflicts.  I don't think the files without supports should be included at all, but I will defer to @cbc02009 on that.

**Comment by CGrassin** [comment]
Since the VORON V0.2 release now natively support the All Metal hot end, this PR doesn't really have reason to exist anymore in my opinion. I believe we can close it. Nevertheless, I solved the merge conflict just in case.

This mod still exists outside of this repository on Printables: https://www.printables.com/model/131985-voron-v01-cr10-hotend-mini-afterburner-mod

**Comment by FHeilmann** [comment]
> Since the VORON V0.2 release now natively support the All Metal hot end, this PR doesn't really have reason to exist anymore in my opinion. I believe we can close it. Nevertheless, I solved the merge conflict just in case.
> 
> This mod still exists outside of this repository on Printables: https://www.printables.com/model/131985-voron-v01-cr10-hotend-mini-afterburner-mod

I agree that this PR can now be closed. I want to thank you for making the effort to submit this PR, even if it ultimately didn't make it into the repo. if you still want to pursue this, I'll do my best to assist you.

**Pull request closed without merging**
