### PR TITLE
20x20mm Profile Covers - Flush and Overlapping

### PR DESCRIPTION
**Pull request by chri-kai-in**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys). - n.a.

#### Which mods/configurations/profiles are added by this PR?
- Provide scalable profiles for covering slots in 20x20x6mm standard construction profiles for VORON printers
- One Type will provide a cover with a 8x1mm cap to overlap the profile surface
- One Type will end flush with profile surface to avoid interference with other moving parts in the printer

#### How was it tested? 
- Printed and mounted on submitters VORON 2.4r1 to cover cables for filament sensor and chamber fan
- Printed OK in AB standard ABS accent color red & eSUN ABS+ black

#### Any background context you want to provide?
- Flush Cover Profile adds value on top of all existing profile covers, as it avoids interference with moving parts on inner side of VORON rack
- Overlapping Cover fits to profiles with 6 mm slots and has been reinforced to avoid easy breaking of clamping arms when mounting
- Can be used with any 20x20mm slot 6 construction profiles

#### Screenshots (if appropriate)
2020_5_Profile_Stealth_Cover_real

### CODE REVIEW

**Comment by cbc02009** [comment]
For some reason this PR includes changes to the angry cam mod. are you sure that's what you want?

**Comment by chri-kai-in** [comment]
No, that would be a mistake and due to my lack of experience with GitHub, Branches, and Push Mechanism. Can/Shall i try to remove the files from the push by ignoring the content in the respective folder, or is there another way of dealing with this issue. Thank You for your support !

**Comment by cbc02009** [comment]
I would:
1. Close this PR
2. back up the files for the PR somewhere
3. delete this branch from both the local and remote
4. pull the latest version of the official repository in using the update button on github for your fork (or delete the fork and creeate a new fork, whichever is easier)
5. make a new branch
6. re-add files
7. push
8. make new PR

right now this PR deletes the angrycam files from the main repo.

**Comment by chri-kai-in** [comment]
Yes, i think that might be the best approach.  - "I will be back" with a new pull request later. Thank You for the clarification and support !

**Pull request closed without merging**
