### PR TITLE
V2.4 Skirt with Switch mod

### PR DESCRIPTION
**Pull request by tayto-chip**
* [ x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ x] Submitted STL files are oriented and scaled properly for printing.
  * [ x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
V2.4 skirts
#### How was it tested? 
300mm skirts used on personal printer. Other sizes not tested. Noted in readme.md
#### Any background context you want to provide?
no
#### Screenshots (if appropriate)
no
#### Further notes
no

### CODE REVIEW

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi, thanks for your submission,

- Please move your mod to a subfolder under your name. Adding another mod will now get confusing since your folder structure looks like this:
```
tayto-chip/250
tayto-chip/300
tayto-chip/350
```
I'd suggest a structure like this:
```
tayto-chip/skirt_switch_mod/250
tayto-chip/skirt_switch_mod/300
tayto-chip/skirt_switch_mod/350
```

- Please add your mod to the top level readme in alphabetical order.

-Florian

**Comment by tayto-chip** [comment]
Florian,

Thank you for the comments. I believe I have made all of the changes requested.

**Comment by FHeilmann** [comment]
Hi @tayto-chip that looks much better. I have one more request:

- Could you add a picture of what the mod looks like installed and maybe describe what type of switch is used in your readme file? That would make the mod much easier to understand by potential users.

Aside from that the PR looks good to me!

-Florian

**Comment by tayto-chip** [comment]
Florian,

Added images and a link to the switch that I used.

**Pull request merged**
