### PR TITLE
C92X_PsycHoShafts_Mount

### PR DESCRIPTION
**Pull request by PsychoShaft**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

Voron 2.4 / Trident or any 2020 profile-based printer, a Mod to help stabilize the Logitech C92X camera range using a 2 axis adjustment.

#### How was it tested? 

Currently fitted and working on my Voron 2.4 350mm Discord: PsychoShaft#1834 V2.3309

#### Any background context you want to provide?

N/A

#### Screenshots (if appropriate)

Screenshots are within the Image folder on my Pull request.

#### Further notes

N/A

### CODE REVIEW

**Comment by PsychoShaft** [comment]
Updated checkboxes all to ticks.

**Comment by cbc02009** [comment]
Your mod should be below Printopal's mods in the readme file. also please include a .step file since not everyone uses fusion 360.

**Comment by PsychoShaft** [comment]
Good evening, I have updated both as requested, Kind Regards Paul

**Comment by cbc02009** [comment]
C92X_Camera_Bracket.stl needs it's orientation fixed. C92X_Extrusion_Bracket.stl is not printable without supports. you should either add printable supports to the file or modify it so that it can be printed without supports.

**Comment by PsychoShaft** [comment]
I have now updated both STEP and F3D files with the additional bracket alongside the STL for a none support print.

**Comment by cbc02009** [comment]
image

seems like there's some issues with C92X_Extrusion_Bracket - No Support Required.stl

Also please remove all spaces from file names.

**Comment by PsychoShaft** [comment]
Sorry about that, should all be sorted now. Thank you

**Review by cbc02009 — APPROVED** [review]

**Pull request merged**
