### PR TITLE
Z-Top Idlers

### PR DESCRIPTION
**Pull request by Itzo1978**
### What mods has this PR added?
Replacing the original Z Idlers with my model

### How has it been tested?
It was tested on my machine, the Voron 2.4 (v2.3941)

### Any context you wish to provide?
I noticed a deformation of the belts. It's moving forwards causing the belt to be a few millimetres out of alignment. Consequence: the Z height cannot be respected without a correction in klipper (with `distance_rotation`)

My model makes it possible to correct this phenomenon

Tightening the screw from above to tighten the belt is much easier than from below.

### Screenshots (if appropriate)
in progress

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [x] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [x] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

### CODE REVIEW

**Comment by jontek2** [comment]
Hey @Itzo1978,

Looks like the bot has spotted issues with the metadata file. Seems like it contains unwanted characters.

I also noted that you uploaded 3mf files, but in the metadata refer to them as stl's. Could you change them to stls?

**Comment by Itzo1978** [comment]
Hey,
I hadn't paid attention to the extension used.
It's been corrected

Thank you for reporting

**Comment by jontek2** [comment]
@Itzo1978 As i was typing i saw that you pushed some changes, hehe. 

Seems like there's still a typo with "cad :" wherte it should be "cad:". I'll run the bot and see if there's any other changes needed aswell.

**Comment by Itzo1978** [comment]
Maybe a anothers problems : a space between Top and Idlers ?
I don't know how to change... I'm discovering these features 🙈

**Comment by jontek2** [comment]
No worries, we'll figure it out.

I belive you have some naming issues with your files vs the yml file. If you look at the yml file it says:

`cad:
- CAD/[a]_z-top_tensioner_9mm_x4.step
- CAD/z-top_tensioner_bracket_a_x2.step
- CAD/z-top_tensioner_bracket_b_x2.step`

Where the actual filenames are:

`
CAD/[a]_ztop_tensioner_9mm_x4.step
CAD/ztop_tensioner_bracket_a_x2.step
CAD/ztop_tensioner_bracket_b_x2.step
`

Please update this and i'll run the bot again.

**Comment by Itzo1978** [comment]
and now ?

**Comment by jontek2** [comment]
Hey @Itzo1978 ,

After internal discussion and review, we've decided to reject this mod submission as it does not meet our submission rules, specifically the "Mods must not represent slight modifications of existing mods/existing VoronDesign printer parts."

However, you're more than welcome to upload it to platforms like Printables or other 3D model databases.

If you have any questions, feel free to reach out to us on Discord.

**Pull request closed without merging**
