### PR TITLE
Simplified Z Drive Motor Mount Bracket and LCD mods

### PR DESCRIPTION
**Pull request by Spaghetti-Bolognese**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
printer_mods/Spaghetti-Bolognese/Z_drive_motor_mount
printer_mods/Spaghetti-Bolognese/LCD_case_mod/

#### How was it tested? 
I've printed the modded parts and tested them on my Voron V2.4

#### Any background context you want to provide?
**Z drive motor mount mod** -  I found it difficult to align the Z drive motor pulley with the 188mm belt on the original design. Any misalignment causes the belt to wonder and rub on the ends of the 16t pulley. I've also found that having a dedicated tensioning cam/lever is not needed and so I combined the two into a single part. I've found my design to be simpler to assemble and align with the belt while maintaining the same belt tension as the original design.

**LCD case mods** - This was originally driven by frustration with installing the hot melt inserts into both the rear and front case parts. I found that they were difficult to align due to the geometry/lack of material. In my opinion they aren't needed because these screws won't be removed often if ever during the case lifetime, so I removed them and resized the holes accordingly. Since I was already changing both the front and rear case parts, I thought I may as well make some cosmetic changes as well, so I added a lip around the LCD and added a cover over the E-stop button.

#### Screenshots (if appropriate)
see README.md for both mods
#### Further notes
My apologies for the number of commits, I'm very new to github!

### CODE REVIEW

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi, thanks for your submission, the PR looks very good! Except for one small detail:

- I see you added an LCD mod, unfortunately you forgot to add this extra mod to the printer_mods readme. Please do so and I'll look to merge your PR ASAP.

Thanks

-Florian

**Comment by Spaghetti-Bolognese** [comment]
Hi Florian, thank you for the positive feedback. I'm new to GitHub and didn't realise I had put the LCD mod under the same PR. I intended for that to be separate as I haven't quite finished that one off yet. I'm on holiday currently but I'll tidy up and finish off the LCD mod when I return next week. Hopefully then both mods can be merged together.

**Comment by FHeilmann** [comment]
@Spaghetti-Bolognese no worries, I'm looking forward to your changes :)

**Comment by Spaghetti-Bolognese** [comment]
Hi @FHeilmann , I have finally got round to updating this pull request as required. Sorry for the long delay! Let me know if any more changes are needed and I'll do my best to follow up more quickly.

**Review by FHeilmann — APPROVED** [review]

**Pull request merged**
