### PR TITLE
Wave share 2k 5.5inch mount

### PR DESCRIPTION
**Pull request by SergeDubovsky**
### Which mods are added by this PR?
WaveShare 5.5" 2k LCD mount for the 2020-framed printers. 

### How was it tested?
Printed, mounted, powered, and set up.

### Any background context you want to provide?
A frame mount is a slight remix of the existing 45-degree mount; it's referenced in the readme. This version uses all available mounting points on the screen. It should be a bit more stiff. 

### Screenshots (if appropriate)
Bottom Assembly

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [x] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [x] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

### CODE REVIEW

**Comment by chirpy2605** [comment]
Hi,

Unfortunately the process for submitting mods has changed recently and it appears that you have submitted the PR using the old instructions.

Can you please resubmit the mod using a fork of the **main** branch and then follow the procedure from here:
https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul#id-like-to-resubmit
And check the submission follows the new rules:
https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules

In particular you should __not__ modify this repos main README.txt anymore (this is done automatically)

**Review by chirpy2605 — CHANGES_REQUESTED** [review]
Hi,

Unfortunately the process for submitting mods has changed recently and it appears that you have submitted the PR using the old instructions.

Can you please resubmit the mod using a fork of the **main** branch and then follow the procedure from here:
https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul#id-like-to-resubmit
And check the submission follows the new rules:
https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules

In particular you should __not__ modify this repos main README.txt anymore (this is done automatically)

**Comment by chirpy2605** [comment]
Hi,

Did you see my comment regarding this PR and the need to re-submit it?

**Comment by raymondh2** [comment]
Hi @SergeDubovsky please see the comments from @chirpy2605 or this pull request will not be merged.

**Pull request closed without merging**
