### PR TITLE
Mak's V0 Mods and Readme update

### PR DESCRIPTION
**Pull request by Makhaira**
Added Mak's first set of V0 mods

### CODE REVIEW

**Comment by FHeilmann** [comment]
@Makhaira do you intend to update this PR to get it merged?

**Comment by Makhaira** [comment]
I will yes, apologies it has been delayed by real life.

**Comment by FHeilmann** [comment]
No worries, whenever you're ready!

**Comment by Makhaira** [comment]
@FHeilmann apologies but as a github noob, how do I go about this please? 

- I'm not sure how to undo just that one line change to the top of readme.md
- I know how to overwrite the STLs and change the file structure, but I don't know how to do it as an update to this PR rather than just a change to my fork and a new PR

Any help on either would be great, thanks!

**Comment by FHeilmann** [comment]
Hi Mak,
ignore the request about the Readme.md, I can fix these issues from here before I merge your PR. In order to update this PR, you basically do the same workflow as you did before you submitted this PR:
- Make your changes
- Create a commit
- Push (sync in github GUI terms) the changes to github

Your PR will update automatically with the new changes.

Bests,
-Florian

**Comment by FHeilmann** [comment]
This PR has become stale and so I'll close it for now. Feel free to reopen or submit a fresh PRt once you get back to it.

-Florian

**Pull request closed without merging**
