### PR TITLE
Single panel magnet

### PR DESCRIPTION
**Pull request by altmank**
* [X ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [X ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ X] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [X ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X ] Submitted STL files are oriented and scaled properly for printing.
  * [X ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Single panel magnet mount mod for 250/300/350 V2.4 sizes
#### How was it tested? 
Printed and tested on a v2.4 300 build
#### Any background context you want to provide?
Magnets are cool, hinges are lame.

### CODE REVIEW

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for your mod!  Please see changes below.

Please remove spaces from your f3d/step filenames.

It would be nice to include a picture of the panel from the backside, showing it mounted to the panel covers.

The bottom of the screw holes in slot STLs has too much overhang, please ensure overhangs are no steeper than 25 degrees.  You can probably just have a 45 degree chamfer there.
Screen Shot 2021-05-02 at 15 48 26

**Comment by altmank** [comment]
I don't know how to achieve the angle you're asking for when chamfering a circle. If that's a blocker, I guess I'll just cancel the PR.

**Comment by altmank** [comment]
Realized my m3 holes in the rail slot were fillets when they should have been chamfers, even named them chamfers but alas they were not. Reexported all the files after making the change.

**Comment by altmank** [comment]
Please let me know if the changes to file names and files resolves the issues preventing adding to the repo.

**Review by KiloQubit — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
