### PR TITLE
Update V1.8 300mm Bed STL

### PR DESCRIPTION
**Pull request by mikepthomas**
* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

Updated the 300mm Voron 1.8 STL for use with Super Slicer. The existing one had the blind joint access holes in the wrong place and the lead screw blocks, bed standoffs and front mount screws were missing

#### How was it tested? 

Imported into Super Slicer (see screenshot)

#### Screenshots (if appropriate)

image

#### Further notes

Is it ok to update the existing file here as I am not the original author or should I upload it into a folder under my own username?

### CODE REVIEW

**Comment by cbc02009** [comment]
@mikepthomas In order to modify someone else's stuff you need to get them to post a comment here saying that it's okay. I would try to contact them here or on discord and see what they say.

**Comment by mikepthomas** [comment]
[tagged on Discord](https://discord.com/channels/460117602945990666/635687829254701107/984004748913037352) If I do not get a reply I will move it into a folder under my own username

**Comment by mikepthomas** [comment]
I have not had any response in dischord from @koonweee so just giving a ping here if that's ok? 

another question would these STL be a better fit [here](https://github.com/VoronDesign/Voron-Extras/tree/main/Bed_Models/SuperSlicer) or is the V1 not here as it is not a "current" model?

**Comment by FHeilmann** [comment]
Hi, 

I want to thank you for your submission and want to personally apologize that your submission has not gotten the review it deserves.
We are in the process to restructure the repo to streamline reviews and hopefully solve this issue in the future.

Unfortunately, this means that we will require you to resubmit the mod under the new system.

Please check [here](https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul) for details and instructions on how to proceed. 
If you have any questions, please reach out in the #voronuser_mods channel on the VoronDesign discord.
If you have since moved on from this mod and don't want to resubmit, no further action is necessary from your side.

Bests,

Florian a.k.a. Haribro

**Pull request closed without merging**
