### PR TITLE
Adding jappaj's FanSaver Mod

### PR DESCRIPTION
**Pull request by jappaj**
* [ x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x ] Submitted STL files are oriented and scaled properly for printing.
  * [x ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
This PR adds the MiniAB FanSaver mod: a printable air dam / heat buffer to prevent 3010 blower fans from overheating
#### How was it tested? 
The mod was printed and tested by a half dozen V0.1 owners and iterated on a number of times to reach its current state
#### Any background context you want to provide?
The FanSaver was created as a way to solve the issue of overheating fan PWM chips without any additional materials to prevent the intermittent slowdown issue that some V0.1 users had reported experiencing (myself included)
#### Screenshots (if appropriate)
N/A
#### Further notes
I only noticed this issue after installing large LED lightbars in my V0.1 enclosure. With the additional light, I was able to see the pip on the face of the blower fan changing speeds even when I had a static fanspeed set in SuperSlicer. I opened a help ticket, and with the help of the Voron team members in the help chat and others on the discord server, I set out to solve the issue with reflective aluminum tape, reflect-a-gold, kapton, and even tiny cut-up heatsinks. I had varying degrees of success with these options before opting to design a printable solution so that others would be able to solve the problem without all the sourcing or fabrication headaches I had run into up to that point.

### CODE REVIEW

**Comment by KiloQubit** [comment]
No 3mf files please, use an STL.

**Comment by nemgrea** [comment]
Can you upload a step file?

**Comment by jappaj** [comment]
Sure thing!

Just swapped out that 3mf for an STL and went ahead and dropped in the step
file as well.

I'm not super familiar with using github; do I need to make another pull
request now that I've modified the files or will it go through as-is with
the modification?

Thanks!

**Comment by KiloQubit** [comment]
> Sure thing! Just swapped out that 3mf for an STL and went ahead and dropped in the step file as well. I'm not super familiar with using github; do I need to make another pull request now that I've modified the files or will it go through as-is with the modification? Thanks!
> […](#)

thanks, no need for a new pull request, it's updated in this one

**Comment by cbc02009** [comment]
Can you verify that the stl is oriented correctly for printing? looks wrong to me.

**Comment by jappaj** [comment]
You're absolutely correct! I must have had it in the wrong orientation when
I exported the STL last time around but I've remedied that and re-uploaded
with a "b" suffix.

**Comment by cbc02009** [comment]
Can you either remove or fix the orientation of the original STL to avoid confusion?

**Comment by jappaj** [comment]
Oh sorry, I did remove the old one when I uploaded the new; the other file
there is just the step file now.

**Comment by cbc02009** [comment]
weird, I don't know what I clicked on then.

**Review by cbc02009 — APPROVED** [review]

**Pull request merged**
