### PR TITLE
LGX Mount for V0.1

### PR DESCRIPTION
**Pull request by VoronMods**
* [x ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ x] Submitted STL files are oriented and scaled properly for printing.
  * [ x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

### CODE REVIEW

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for your mods!

Please remove spaces from all directory names.

Please remove the empty README.md in the LGX mount directory/STL/.

Please add links to your mods to `printer_mods/README.md` in alphabetical order.

7x7 chain ends - both have overhangs that are too steep, please ensure overhangs do not exceed 45 degrees, and the OUT end also has unsupported overhangs on the side knobs:

Screen Shot 2021-08-29 at 15 32 31

Screen Shot 2021-08-29 at 15 36 26

Please rename `LGX_strain_relive.stl` to `LGX_strain_relief.stl`.

`LGX_X_carriage_back_plate.stl` has unsupported overhangs:
Screen Shot 2021-08-29 at 15 59 19

`LGX_Y_Endstop_Bumper.stl` has unsupported overhangs:
Screen Shot 2021-08-29 at 16 01 59

Also see README changes below.

**Comment by VoronMods** [comment]
Fixed names and overhangs for LGX, removed the 7x7 end chains as I don't have time to redesign it

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for the updates!

- Please add a link to your mod to `printer_mods/README.md` in alphabetical order
- `LGX_Y_Endstop_Mount_x1.stl` is not in a printable orientation

**Comment by VoronMods** [comment]
mod added to printer_mods/README.md in alphabetical order and Y end stop orientation fixed

**Review by KiloQubit — CHANGES_REQUESTED** [review]
@VoronMods looks like `LGX_Cowling_V0.1.stl` has errors, please fix.

```
Validating STL printer_mods/MikesMods/LGX_mount_for_V0.1_with_2nd_X_rail/STL/LGX_Cowling_V0.1.stl
  !! Detected "Edges fixed" value of 4
```

**Comment by VoronMods** [comment]
sorry, don't know where the error comes from, how do you test? I can't confirm this error.

**Comment by KiloQubit** [comment]
> sorry, don't know where the error comes from, how do you test? I can't confirm this error.

We have an automated workflow in Github that checks this, but you can also see the error if you open the STL in PrusaSlicer:
Screen Shot 2021-09-23 at 12 40 39

**Comment by VoronMods** [comment]
Thanks, I can see now the error in slicer, I think I've ignored them or did not see it. Errors are fixed now.

**Review by KiloQubit — APPROVED** [review]
Thanks for the update!

**Pull request merged**
