### PR TITLE
Initial commit of files for laser cut door panels for better fit on 2.4.  Might work on others.

### PR DESCRIPTION
**Pull request by jotpowers**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

Creates DXF files for laser cutting the front acrylic door panels that are stock to allow for the other usermod hinges (Randell, 270 parametric) to be mounted and adjusted.  

#### How was it tested? 

Cut and installed on my 300mm 2.4.  Also includes a modified door latch to allow the panels to fit tighter, since they still had gaps when I installed them.

### CODE REVIEW

**Comment by jotpowers** [comment]
Um... I just rebased, so might have messed up this PR.  LMK if that's the case and we can cancel and I can create  clean one.  Github:  Not my strength.

**Comment by clee** [comment]
> Um... I just rebased, so might have messed up this PR. LMK if that's the case and we can cancel and I can create clean one. Github: Not my strength.

You shouldn't need to cancel the PR, but this is definitely a bit of a git mess. If you can get the history clean on your side, you should be able to `git push --force` to update this PR and clean it up without deleting the PR and creating a new one. Ping me on Discord (`clee#1337`) if you need some help with git.

**Comment by jotpowers** [comment]
I'll take a quick swing at cleaning it up.  Quick google indicates it might not be too bad, but if it's a bunch of work, it's no big deal to close and open a new one.

**Comment by jotpowers** [comment]
Ok, spent some time looking and think I see how I can avoid this in the future, but for now, way too much work.  So I'm going to close and will open a new PR.  Thanks for the offer to help  online.

**Comment by jotpowers** [comment]
Ok, spent some time on this, and in the end decided it was easier to close
the request and start over.  So, there is a new PR with the same content
that is hopefully clean.

Thank you for the offer to help with the git stuff.

**Pull request closed without merging**
