### PR TITLE
PEI stop

### PR DESCRIPTION
**Pull request by Itzo1978**
### Which mods are added by this PR?
It's a little help for positionning the PEI Plate

### How was it tested?
On my machine (v2.3941) since october 2013

### Any background context you want to provide?
The stop I've developed makes the Y position easier to see (especially on the 2.4 350).

### Screenshots (if appropriate)
Presented in images in the `readme`

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [x] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [x] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

### CODE REVIEW

**Review by jontek2 — COMMENTED** [review]
@Itzo1978 Looks good, but could you update the name? It currently says "New mod : PEI Stop" but "PEI stop" would be better.

**Review by mjonuschat — APPROVED** [review]
LGTM

**Comment by Itzo1978** [comment]
> @Itzo1978 Looks good, but could you update the name? It currently says "New mod : PEI Stop" but "PEI stop" would be better.

Done ✅️

**Review by jontek2 — APPROVED** [review]
LGTM!

**Pull request merged**
