### PR TITLE
Update to my connector cover to fit v2.4

### PR DESCRIPTION
**Pull request by hhammarstrand**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
A connector cover for 42STH20-1004AS to use with the Afterburner

#### How was it tested? 
Tested by me and a few users on the discord. I'm not sure it has been tested on 1.8 or 2.4, but it has been tested on the switchwire (which is missing in the compatibility table here in voronusers?)

#### Any background context you want to provide?
I have been asked for this connector cover multiple times on discord, that's why I'm submitting this, to have a place with all the info and latest versions. 

#### Screenshots (if appropriate)
compare

#### Further notes
I also changed a bit in my folder structure and file naming so that it's a little cleaner. Hope that doesn't complicate things?

### CODE REVIEW

**Comment by afewyards** [comment]
there is some interference between the igus cable chain and this mod on the 2.4. it hits the angled part for about 0.5-1mm

**Comment by jason7594** [comment]
Awesome!

**Comment by KiloQubit** [comment]
There's another mod that modifies your cover to fit on the 2.4 - https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/buzzdalf/connector_cover .  Can you work together with buzzdalf to create a single unified mod?

**Comment by hhammarstrand** [comment]
> There's another mod that modifies your cover to fit on the 2.4 - https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/buzzdalf/connector_cover . Can you work together with buzzdalf to create a single unified mod?

It would probably be better just to refer to the pinned message in #ldo_motors on Discord since Steve has made a new version that I guess is official? 

Direct link: https://discord.com/channels/460117602945990666/710952853514223617/819046065985683476

**Comment by hhammarstrand** [comment]
> @hhammarstrand now that the the new cover is official, I want to close this PR unless there's some advantage to your cover over the official one. Any objections?
> 
> https://github.com/VoronDesign/Voron-2/blob/Voron2.4/STLs/VORON2.4/Gantry/X_Axis/X_Carriage/Direct_Feed/%5Ba%5D_connector_cover.stl

No objections!

**Pull request closed without merging**
