### PR TITLE
Add a stealthburner toolhead for creality e3 hotend.

### PR DESCRIPTION
**Pull request by strayr**
* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folder and file naming:
    * Folders and filenames shouldn't contain spaces. Only letters `a-zA-Z`, numbers `0-9`, underscores `_`, hyphens `-` and periods `.`
    * Primary color: `part_xyz.stl`
    * Accent color: `[a]_part_xyz.stl`
    * Opaque color (Blocks light): `[o]_part_xyz.stl`
    * Clear/transparent color (Allows light): `[c]_part_xyz.stl`
    * Quantity, if more than one is needed: `part_xyz_x4.stl`
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
printer_mods/strayr/stealthburner_creality_toolhead

#### How was it tested? 
in use on my VS373, abbn version previous to this has hundreds of hours on my printers and appears to be in use or have been in use with a few users. Have been refusing to release a stealthburner until the cad was available.

#### Any background context you want to provide?
This hotend works very well with slice heatbreaks and is entirely made of sunk cost fallacy. Using a 0.6 CHT nozzle in this and getting quite impressive results.

Whilst I'd never recommend buying this hotend, there's a strong ender3 -> switchwire community and I maintain an afterburner carriage for ender 3 (and apparently it fits ender 5) that preserves the modularity of the original design rather than modifying the extruder and/or the back of the toolhead. I consider this important as part of a gentle entry to voron, I tried out lots of toolheads until i found one that was easy to work on and had good enough PLA performance before I started putting money into printers.

#### Screenshots (if appropriate)
photos are included

#### Further notes
I'd love some feedback on the quality of my submission even if it's not appropriate for here. If the fusion360 source is too big and you'd prefer step or would like step as will i can do that. I don't really consider step "source" though.

### CODE REVIEW

**Review by newphreak — CHANGES_REQUESTED** [review]
printer_mods/strayr/stealthburner_creality_toolhead/cad/Stealthburner_Printhead_Creality-1 v9.f3z <- remove the spacing in the filename. exporting as .step would also be preferred as more people can use it.

image
Pretty sure the nozzle should be 2mm below the ducts for optimal placement, I will doublecheck that. And it should be better documented in the readme. So screw BOM and a little guide on how to get to a good place would be best.

image
On the front: Make the hole slightly bigger to remove the small bridge for printability.

image
On the rear: printability could be somewhat improved in these two ares. It's better to cut a little more, chamfer it and make it bridge.

**Comment by newphreak** [comment]
image
This is the optimal distance

**Comment by strayr** [comment]
It's matched to the nozzle position of a v6, I work backwards from a V6
reference cad and toolhead position when jointed to that.

Will confirm the measurements in the cad and with photo of my in use parts.

Should I make it clearer that moving the heater block by using a v6 nozzle
doesn't change the overall length appreciably, just where it sits in the
threads?

**Comment by newphreak** [comment]
image
Unless the angle is really playing tricks here this doesn't seem to be 2.8mm further down.

Either way, that would be an end-goal for this.
Also you're correct in the heatbreak threading further down or up doesn't change the distance, it just moves the heater block, unless you also move the heatbreak, in which case it does change things.

Since the people this is tailored for may lack knowledge/ingenuity in some cases i do want things to be documented well and somewhat foolproof. So things that can be done wrong are documented and accounted for.
People may come in here with different heights on the heatbreak for one, so measurements and a small checklist to get to an optimal place right away is what I'm barking at. In which case "recommending" v6 nozzles should then be made a requirement. Unless you document distances for both mk8 and v6 styles.

That got a little messy, but hope you follow what I'm getting at :)

**Comment by strayr** [comment]
I've got a problem here with the supplied dimensions, I have 61.5mm between
the nozzle tip and the flat surface at the top of the toolhead, which makes
the duct tips 0.43mm below the specified 2.8mm. This is with a BMS toolhead
from RC1 stealthburner step as a starting point.

**Comment by strayr** [comment]
OK, wile.e says the 61.5mm is the reference dimension, will document
thoroughly

**Comment by strayr** [comment]
Ok, this should be good to recheck, sorry for the multiple commits, a git sparse-checkout did odd things to me merging from my work branch to my PR branch. The end result is the same when the commits get squashed. I'm not super used to sparse-checkout but it's really handy for big repos on limited hardware.

**Comment by newphreak** [comment]
That's looking much better. Instead of the f3z which imports 4 projects, can you make one with a master assembly only? No need for a bunch of separate items. That goes for the .step too. It makes it so much easier to look at it.

**Comment by strayr** [comment]
Are you asking me me to break the links on the source objects so they are contained within the single file, or to remove the the parts I'm using as reference geometry?

**Comment by newphreak** [comment]
I'm trying to figure out a good way to do this and make it an requirement to mods to keep the number of steps down. I dont have a good answer YET. But what if you make a new cad, import the mods, sort them under different components, and each component can have sub-components (the different parts). It makes the workflow of both reviewing and later on editing/expanding a lot easier. I'm learning along with you on this one, I just want things to be easier for everyone involved.

**Comment by strayr** [comment]
I'll have a look at cleaning up my .f3d , I made the pressure version by
abusing my history and what I really need to do is copy the bodies to a new
component.

I consider the step produced by fusion 360 an output format as it loses the
history, joints and sketches that were used to produce the STL. It's a good
thing to have usable cad, but I'm not sure it's GPL compatible to remove
anything.

Whilst my first degree was mech eng in the days of SDRC i-DEAS I'm much
more used to software engineering, and it's healthy if not essential here
to maintain good logical separation between your (organisation's) own work
and contributory source. I'm not sure fusion lets you relink geometry
against a different reference model though, it's still very waterfall so
there's less harm to the source, but it feels like plagiarism and I think
if external parts are used for reference and copied rather than importing
they need to be explicitly referenced.

Why is this important? Do I break a GPL project by reuse of parts with an
incompatible license? I have specific hatred of parts derived from GPL that
are relicensed as cc-by or cc-by-nc as it's not compatible with GPL which
forbids stipulations on how the source or object is used.

**Comment by newphreak** [comment]
It's not at all, this is all me trying to figure out a way to speed up both reviewing and editing later on. I think it's good as is, but since step files have most names, references and things removed i think using components to make it all in one is the best way to get an overview quickly. All that said that's probably best left for future things once things are figured out. Sorry again for you ending up being my experimental learning step. F3D is definitely beneficial for fusion users, but also not required. I'm glad to see people including them regardless. As for GPL compliance, I dont know. Still figuring things out.

**Comment by newphreak** [comment]
And one last question before i approve, is this little lip inside the front parts a leftover artifact or intentional?
image

**Comment by strayr** [comment]
Issues addressed as per commit note

**Review by newphreak — APPROVED** [review]
💯 Perfection. Looks good to me. Sorry for all the noise in this one.

**Review by cbc02009 — CHANGES_REQUESTED** [review]
can you just mention in the mod's readme which stealthburner revision this is modeled on so that people can print out the front that fits? (I believe we're at RC1, but I would double check)

**Comment by strayr** [comment]
> can you just mention in the mod's readme which stealthburner revision this is modeled on so that people can print out the front that fits? (I believe we're at RC1, but I would double check)

Done. I didn't think it was an issue as we weren't doing cad files and public mods for beta. RC1 toolheads fit beta fronts but beta toolheads don't fit RC1 fronts. 

Is *mechanically compatible* enough of a hint that it doesn't look great with beta?

**Comment by cbc02009** [comment]
This is really just in case there's some major change with RC2 or some future release, not for backwards compatibility with beta

**Comment by strayr** [comment]
then i think we're good either way?
https://github.com/VoronDesign/VoronUsers/pull/805/commits/4f332c39a44c85eb833c5ef8295f0d673d336dc9

**Review by cbc02009 — APPROVED** [review]

**Comment by strayr** [comment]
Thanks!

**Comment by strayr** [comment]
I've fixed the STLs failing the workflow test, it looks like i forgot to redo the netfabb fix when i removed this artefact. https://github.com/VoronDesign/VoronUsers/pull/805#issuecomment-1241164618
 Oh for toolchain automation.

**Pull request merged**
