### PR TITLE
Bracket for Octopus (PRO) Boards

### PR DESCRIPTION
**Pull request by DaStivi**
*  [x] The mod, firmware configuration or slicer profile is in the correct category folder. Printable mods go to `printer_mods/`, firmware configurations  go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
"Octopussy" - Bigtreetech Octopus (PRO) Board Bracket

#### How was it tested? 
ah couple of Users including me using the brackets/mounts

#### Any background context you want to provide?
created way back where Octopus boards where fairly new, just posted in Discord ah couple of times, never got over how Github work

### CODE REVIEW

**Review by DaStivi — COMMENTED** [review]
missunderstood first time maintainer approve... ~~double checked everthing should be fine~~

**Comment by cbc02009** [comment]
These are very nice, but I'm hesitant to merge them in knowing that the v2.4r2 will use the trident electronics brackets. I would either update them for the new brackets, or maybe link to the specific commit of the current din rails so people can find them.

Also please change the mod name.

**Comment by DaStivi** [comment]
> These are very nice, but I'm hesitant to merge them in knowing that the v2.4r2 will use the trident electronics brackets. I would either update them for the new brackets, or maybe link to the specific commit of the current din rails so people can find them.
> 
> Also please change the mod name.

changed name, linked to r1 din clip and r2 din clips

**Review by cbc02009 — APPROVED** [review]

**Comment by DaStivi** [comment]
sorry about defective stl " Detected "Backwards edges"  not sure what was really the problem.. got it repaired with windows 3d builder, looks like superslicer didn't made it correct... 🤷‍♂️

**Pull request merged**
