### PR TITLE
V0.1_Skirt_Mods

### PR DESCRIPTION
**Pull request by 3vilson**
* [X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [X] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [X] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [X] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X] Submitted STL files are oriented and scaled properly for printing.
  * [X] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Skirt Mods
#### How was it tested? 
Printed it
#### Any background context you want to provide?
no
#### Screenshots (if appropriate)
no
#### Further notes
no

### CODE REVIEW

**Review by cbc02009 — CHANGES_REQUESTED** [review]
Please add this mod to the printer_mods/readme.md file as specified in the checklist

**Comment by cbc02009** [comment]
Also please remove all spaces from file and folder names

**Comment by cbc02009** [comment]
Your PR is modifying other people's mod entries in the main readme.md file. can you remove those changes so it only changes your own entry?

**Comment by 3vilson** [comment]
> Your PR is modifying other people's mod entries in the main readme.md file. can you remove those changes so it only changes your own entry?

Please check it again if I did it right :(

**Comment by cbc02009** [comment]
this time you deleted all the other entries in the table. grab the latest copy of readme.md from here: https://raw.githubusercontent.com/VoronDesign/VoronUsers/master/printer_mods/README.md and add your entries to it and commit.

**Comment by 3vilson** [comment]
> this time you deleted all the other entries in the table. grab the latest copy of readme.md from here: https://raw.githubusercontent.com/VoronDesign/VoronUsers/master/printer_mods/README.md and add your entries to it and commit.

Should i put it inside the list or above ?

**Review by cbc02009 — CHANGES_REQUESTED** [review]
readme should be good now, but most of your STLs are upside down. please double check them and make sure they're oriented correctly.

**Comment by 3vilson** [comment]
> readme should be good now, but most of your STLs are upside down. please double check them and make sure they're oriented correctly.

Done :)

**Comment by cbc02009** [comment]
orientation is still wrong:
image

**Review by cbc02009 — APPROVED** [review]

**Pull request merged**
