### PR TITLE
Mod for door hinges which uses 35mm M3 screw to prevent breaking

### PR DESCRIPTION
**Pull request by Mosher23**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
its a door hinge mod which uses 35m Socket head M3 screw instead all print-in-place hinge. 
#### How was it tested? 
on my Voron v2
#### Screenshots (if appropriate)
Door Hinges mod with M3 35mm

### CODE REVIEW

**Comment by Mosher23** [comment]
changes done, please review them

**Comment by randellhodges** [comment]
If you have a fusion 360, or step file, would you please include that? It'll help if others need to make small tweaks for their setup.

**Comment by FHeilmann** [comment]
Thanks for updating the mod. Unfortunately all the parts are not oriented correctly. Please fix the orientation. You also included a picture in your mod, it would be nice if it was shown in the readme inside your mod folder!

Otherwise the mod looks good to me, once you fix the orientation I'll look to merge ASAP. Let me know on discord if you need any help.

-Florian

**Comment by Mosher23** [comment]
hey, i changed the positions of the STLs and added an image to README.md

**Pull request merged**
