### PR TITLE
updated .dxf file

### PR DESCRIPTION
**Pull request by oookamiii**
updated one file that was missing the 76mm hole

### CODE REVIEW

**Comment by newphreak** [comment]
Looks good to me, I only have one question since this 3dpandme seems to be a collected "user", can anyone of the previous guys confirm this is okay? @dmason1992 @rr-david

**Comment by newphreak** [comment]
#815

**Comment by dmason1992** [comment]
Hi,

This is correct. I provided him with the corrected file. I raised the issue but hadn't got around to putting in a PR fix. Thank you for fixing doing this @oookamiii

**Review by cbc02009 — APPROVED** [review]

**Comment by cbc02009** [comment]
closes #815

**Pull request merged**
