### PR TITLE
Added V0 direct drive mod

### PR DESCRIPTION
**Pull request by kirby6365**
Added modified fan shroud and hotend mounts for dragon hotend to convert V0 to a direct drive.

  * [X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [X] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [X] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [X] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X] Submitted STL files are oriented and scaled properly for printing.
  * [n/a] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Added v0_sherpa_mini_direct_drive

#### How was it tested? 
Printed and tested for ~20 hours of printing thus far. No issues thus far.

#### Any background context you want to provide?
n/a

#### Screenshots (if appropriate)
n/a

### CODE REVIEW

**Comment by VinnyCordeiro** [comment]
Which variant of the Sherpa extruder is to be used?

**Comment by kirby6365** [comment]
The Annex Sherpa Mini, as stated in the description and readme :)

**Comment by VinnyCordeiro** [comment]
Just now I discovered that there is the Sherpa Extruder and then the Sherpa Mini-extruder. D'oh!

Looks like I'll have to buy the right stepper motor for it, the one used on the Pocketwatch does not fit.

**Comment by mvrckcompany** [comment]
The file "v0_direct_drive.step" produces an error while attempting to open in Fusion 360. 

image

**Comment by kirby6365** [comment]
Opens perfectly fine into Fusion360 for me. Just retested it with the web-based github one. Are you sure you're opening it correctly F360?

**Comment by mvrckcompany** [comment]
I downloaded again and it opened fine. Sorry about that!

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi, thanks for the submission of your mod. I have two points:

- Both `v0_dd_hotend_left.stl` and `v0_dd_hotend_right.stl` have sections that basically have to be printed in midair. I have marked them in the screenshot below: 
image
While I'm sure the parts will recover in most cases, fixing these sections should be easy by removing the overhanging parts of the screw holes like so:

image

- The second point is the trickier one, unfortunately. Since you are acquainted with AnnexEngineering, you probably know about the Annex EULA most of their released designs are licensed under. Any mod submitted in this repository automatically falls under the associated license: GPLv3. Being a hobbyist and no lawyer, I don't know what the implications are here, so I am in the unfortunate position to make the following request:
  - Please ask the owner of Annex-Engineering whether they authorize the submission and GPLv3-licensing of this mod, which interfaces Annex-Engineerings Sherpa Mini design licensed under the Annex EULA. You can either submit any positive response here so it can easily be found next to your mod, or share it with me on discord so I can provide it to anyone who may request it.

Sorry for the inconvenience, I am looking forward to your reply. Feel free to ping me on discord, too.

-Florian

**Comment by kirby6365** [comment]
Hey Florian,

Just pushed an update to fix the overhang issues.
For the second point, per discussion with the Annex folks, they have stated they do not require permission/authorization to create mods for a toolhead they didn't create, even if it links/or is intended to go with the Annex Sherpa Mini.  Since it is fully derived from the Voron V0 toolhead and doesn't include the Annex Sherpa Mini in either the step file or any of the stls, there's no issue.

Let me know if you have any questions or concerns with the above; can always reach me on Discord as well.

**Comment by kirby6365** [comment]
Screenshot_20201001-080804

Per request here's a screenshot of discussion with Annex devs about specific permission/allowing of this mod.

**Review by raymondh2 — APPROVED** [review]

**Pull request merged**
