### PR TITLE
Adding Misumi shoulder bolt mods for v2.4

### PR DESCRIPTION
**Pull request by randellhodges**
* [X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [X] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [X] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [X] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X] Submitted STL files are oriented and scaled properly for printing.
  * [X] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

An alternative to the pins mod, this uses Misumi shoulder bolts.

#### How was it tested? 

Printed and used on my printer for the past year

#### Further notes

This was mentioned in various Discord channels and used by a few people but I forgot to actually submit a pull request.

### CODE REVIEW

**Comment by jlas1** [comment]
All the STL's have no errors, The CAD is included.

**Comment by randellhodges** [comment]
This fell off my radar. I did even notice the "Action required by maintainers" label until jlas commented. What is required? I guess maybe that since this was originally done for the first released version of 2.4, maybe it is sort of out of date?

**Comment by cbc02009** [comment]
@randellhodges action required by maintainers means we have something to do to finish up the PR, not you. Sorry this has sat so long.

**Comment by cbc02009** [comment]
Do you know if this is compatible with v2.4r2?

**Comment by randellhodges** [comment]
I do not know. I haven't looked at all the changes between initial 2.4 release and subsequent r1 and r2 releases. I sold the printer that I did this mod to, and my new one uses the pin mod instead.

**Comment by cbc02009** [comment]
If you still want to submit this mod I would just add a bolded warning in the readme that this mod was only tested with r1 and may not work with r2.

**Comment by randellhodges** [comment]
> If you still want to submit this mod I would just add a bolded warning in the readme that this mod was only tested with r1 and may not work with r2.

Good idea. I'll get it updated soon and let you know.

**Comment by randellhodges** [comment]
> If you still want to submit this mod I would just add a bolded warning in the readme that this mod was only tested with r1 and may not work with r2.

Good idea. I'll get it updated soon and let you know.

**Comment by FHeilmann** [comment]
@randellhodges as there was no activity for 1 year I'm closing this PR. If you'd still like to submit your mod, please reach out to me on discord (Haribro)

**Pull request closed without merging**
