### PR TITLE
Rs 50 5 bracket

### PR DESCRIPTION
**Pull request by Rikers-Beard**
### Which mods are added by this PR?
     This PR adds a Meanwell RS-50-5 PSU DIN rail mount bracket.
### How was it tested?
     I printed this bracket out, installed it on my RS-50-5 PSU, and finally installed the assembly onto the DIN rail in my V2.4r2
### Any background context you want to provide?
     I initially tried the old RS-25-5 bracket and found it to be more wobbly on the DIN rail than I liked, this holds the bigger PSU nicely.
### Screenshots (if appropriate)
     
mounted

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [X] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [X] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

### CODE REVIEW

**Comment by jontek2** [comment]
Hi @Rikers-Beard,

The CI-bot has detected an issues, could you please attend to that?

Also a few minor details i've noticed upon review:

- Your discord_username is probably wrong, seems like you put the screenname and not the username.
- Any reason for not including the trident in "Printer Compability"?

Other than that it looks good to me!

**Comment by Rikers-Beard** [comment]
Hi, thanks for reviewing my submission. This is my first time submitting
mods, sorry for any hiccups.

1.) I go by "Riker's Beard" on the voron discord and other related 3D
printing channels. My discord username wasnt as "family friendly", I've
changed it to be more relevant and will update my two submissions now.

2.) I only listed V2.4r2 compatibility because the guide states to "Please
only specify printers that you have either tested your mod on yourself, or
that someone else has tested for you". I have not found anyone else to test
this mod for me yet, I will add "VT" and others with your approval.

Thanks for your help, feel free to revise printer compatibilities as you
see fit from your end if possible.

**Comment by Rikers-Beard** [comment]
Okay username is corrected in the metadata.yml, added VT to list of compatibilities, this one should be good to go now. I also corrected the metadata in my other pending submission. Thanks.

**Comment by Rikers-Beard** [comment]
I'm confused as to why I am still getting errors on the checklist, I followed the sample_mod template and organized the file structure as directed. I'm standing by to make the necessary corrections.

**Comment by jontek2** [comment]
Thanks for the updates. I think the error lies in description in the metadata-file, could you please try a shorter? Maybe something like "A Meanwell RS-50-5 PSU DIN rail mount bracket" or something? Longer text can be put in the README-file.

**Comment by Rikers-Beard** [comment]
Okay, that makes sense. I'll revise both mod submissions accordingly. Thank you.

**Comment by Rikers-Beard** [comment]
Both PRs revised.

**Review by jontek2 — APPROVED** [review]
LGTM!

**Review by mjonuschat — APPROVED** [review]
Looks good to me.

**Pull request merged**
