### PR TITLE
Skirt storage for Voron2 350

### PR DESCRIPTION
**Pull request by ScramblerUSA**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Skirt storage compartment for Voron2 350

#### How was it tested? 
Printed and installed in my printer

#### Any background context you want to provide?
A small storage compartment akin to Ender3 V2 toolbox. Finally it is possible to store all hex keys, cleaning needles, spare nozzles, etc. right here in the printer.

### CODE REVIEW

**Comment by newphreak** [comment]
Thank you for submitting this mod.
image
This could probably do with some minor printability tweaks, Would also love a .4 chamfer on the whole bottom.

**Comment by ScramblerUSA** [comment]
> This could probably do with some minor printability tweaks,
Are there any printability issues though? These tiny overhangs only protrude slightly from the wall, which gives them enough support, I think. At least that was an idea behind such a shallow web. Here are your circled areas on a print:
image

If you still think it's bad - any suggestions on how to make it better?  The only idea I have is to print the web separately and glue it on, but I don't like this idea at all.

> Would also love a .4 chamfer on the whole bottom.
It has a 1 mm fillet on the bottom. Is fillet not good?

**Comment by stvptrsn** [comment]
> > This could probably do with some minor printability tweaks,
> 
> Are there any printability issues though? These tiny overhangs only protrude slightly from the wall, which gives them enough support, I think. At least that was an idea behind such a shallow web. Here are your circled areas on a print: image
> 
> If you still think it's bad - any suggestions on how to make it better? The only idea I have is to print the web separately and glue it on, but I don't like this idea at all.
> 
> > Would also love a .4 chamfer on the whole bottom.
> 
> It has a 1 mm fillet on the bottom. Is fillet not good?

Cool mod!  I'd probably flatten your hex pattern out so it's easier to print.  Maybe even chamfer the inside edges so they're all supported.  I think the mod would still look ok without it following the exact same fillet setup as the rest of the skirts and will make those overhangs less of an issue..

Never put fillets against the print surface, use chamfers instead.

Steve

**Comment by ScramblerUSA** [comment]
Thank you for your inputs, Steve. Fillet on the bottom = never, noted. Chamfering the bottom of those overhangs is a very good idea!

**Comment by FHeilmann** [comment]
Hi, 

I want to thank you for your submission and want to personally apologize that your submission has not gotten the review it deserves.
We are in the process to restructure the repo to streamline reviews and hopefully solve this issue in the future.

Unfortunately, this means that we will require you to resubmit the mod under the new system.

Please check [here](https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul) for details and instructions on how to proceed. 
If you have any questions, please reach out in the #voronuser_mods channel on the VoronDesign discord.
If you have since moved on from this mod and don't want to resubmit, no further action is necessary from your side.

Bests,

Florian a.k.a. Haribro

**Pull request closed without merging**
