### PR TITLE
Kirigami bed front

### PR DESCRIPTION
**Pull request by Kosh42**
* [ Y ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ Y ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ Y ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ Y ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ Y ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ Y ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ Y ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ Y ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ Y ] Submitted STL files are oriented and scaled properly for printing.
  * [ NA ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Kirigami bed front printable mod.

#### How was it tested? 
I have it on a working machine.

### CODE REVIEW

**Comment by hdtechk** [comment]
I was only able to make this fit after cutting away the sides as shown in photo 
PXL_20211128_192039976

**Comment by hdtechk** [comment]
PXL_20211128_192823731

**Comment by Kosh42** [comment]
Damn. Printed and on fine for me.

**Comment by hdtechk** [comment]
maby this screenshot will help the circles show where interfirance is that wont let it sit flat and flush
Screenshot 2021-12-01 220422

**Comment by Kosh42** [comment]
Model updated to account for the problems.

**Comment by falo2k** [comment]
I had the same issue with the original.  New model now fits perfectly.  Cheers.

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Please remove spaces from CAD filename.

Unsupported overhangs on the bottom side of the hex nut holes
Screen Shot 2021-12-06 at 19 49 18

**Comment by Kosh42** [comment]
@KiloQubit - Should be addressed in latest commit: https://github.com/VoronDesign/VoronUsers/pull/537/commits/d8082c3d211ae87f737dd3873b2f4c57abb3dfff

TY for the feedback.

**Review by KiloQubit — APPROVED** [review]

**Pull request merged**
