### PR TITLE
V1.8 adaption

### PR DESCRIPTION
**Pull request by Exerqtor**
Adapted a stock right side V1.8 x-carriage mount to fit your BLTouch mounting solution. 
Also added a notch in the BLTouch mount to allow the x-endstop cables to pass thru. 

[BLtouch x-carriage.zip](https://github.com/VoronDesign/VoronUsers/files/6976103/BLtouch.x-carriage.zip)

### CODE REVIEW

**Comment by KiloQubit** [comment]
There appear to be two mods here, one in the `printer_mods/issic/AfterburnerNew/` directory and one in the `printer_mods/issic/V2.4_BLTouch_X_Carriage/` - are both of these part of this mod?  If only one is part of this mod, then please remove the other one from this git branch.

Also I'm a bit confused about why user @Exerqtor is opening a pull request from a repository of user @issic .

**Comment by Exerqtor** [comment]
Yeah i'm sorry i tried to delete this since i saw it got all messed up. I tried to submit a mod i made for @issic's 2.4 BLTouch mod so that it could be used for the 1.8.

**Comment by KiloQubit** [comment]
> Yeah i'm sorry i tried to delete this since i saw it got all messed up. I tried to submit a mod i made for @issic's 2.4 BLTouch mod so that it could be used for the 1.8.

So you made a mod of issic's mod?  Did you put it in issic's repository?  Are both your mod and issic's mod in that repository?  I don't see commits from you in issic's repository.  I also don't see issic's mod in VoronUsers, maybe it was never submitted.

**Comment by Exerqtor** [comment]
I tried but i didn't get it to work 🤦‍♂️ But yeah i don't think he's
submited it, i found it thru a google session. You can close this whole
request if you want to. I have the file on my computer if you would want to
put it out there tho. But with trident being released i feel like it's
kinda depricated now. Also it won't work with MGN12 rails due to the space
constraints.

søn. 29. aug. 2021, 20:58 skrev KiloQubit ***@***.***>:

**Comment by issic** [comment]
What is happening? ;-)

Yes i didn’t committed to master, it’s still in mine fork

**Comment by KiloQubit** [comment]
@Exerqtor in the future please do not submit pull requests against other people's forks without asking them first.

I'm going to close this PR.  @issic if you want to submit your own changes, you can make your own PR for them, though I'm not sure if this mod is still relevant with the release of Trident.

**Pull request closed without merging**
