### PR TITLE
SB+CW1+PCB Cover Added

### PR DESCRIPTION
**Pull request by wile-e1**
Added a low-poly style cover for users that are still rocking the Clockwork1 and PCB with Stealthburner.  This should be compatible with ERCF and Hartk style PCBs.

image

image

image

### CODE REVIEW

**Comment by cbc02009** [comment]
looks like there are some merge issues with the main printer_mods/readme.md file that need fixing.

**Comment by wile-e1** [comment]
> looks like there are some merge issues with the main printer_mods/readme.md file that need fixing.

I looked at the merge conflict on the readme, but I can't figure out what it's actually asking for.

**Comment by cbc02009** [comment]
image
It looks like there's a bunch of extra formatting of the usernames in your version (extra spaces for alignment). I can fix it from the github gui if you want me to.

**Comment by cbc02009** [comment]
```  printer_mods/README.md
    358:5-358:77  warning  Link to unknown file: `wile-e1/stealthburner_cw1_pcb_cover`. Did you mean `wile-e1/Stealthburner_CW1_PCB_Cover`  missing-file  remark-validate-links``` CI found a bad link.

**Review by cbc02009 — APPROVED** [review]

**Pull request merged**
