### PR TITLE
Add SKR E3 DIN mount to printer_mods

### PR DESCRIPTION
**Pull request by masimplo**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
This PR adds a DIN mount for the BTT SKR E3 family of boards. 

#### How was it tested? 
I have mounted an SKR E3 Turbo on a printed part from the included STL which I connected with a Voron DIN clip (https://github.com/VoronDesign/Voron-1/blob/Voron1.8/STLs/Electronics_Brackets/Rear_Electronics_Enclosure/pcb_din_clip_x3.stl).

### CODE REVIEW

**Review by KiloQubit — COMMENTED** [review]
Is this just for the SKR E3 Turbo, or for the regular E3 as well?  The name of the mod implies that it's for a regular E3.  If that's the case, there's already a mount for that included in the Voron-2 repository:

https://github.com/VoronDesign/Voron-2/blob/Voron2.4/STLs/VORON2.4/Electronics_Compartment/DIN_Brackets/skr_mini_e3_bracket_x2.stl

**Comment by masimplo** [comment]
> Is this just for the SKR E3 Turbo, or for the regular E3 as well? The name of the mod implies that it's for a regular E3. If that's the case, there's already a mount for that included in the Voron-2 repository:
> 
> https://github.com/VoronDesign/Voron-2/blob/Voron2.4/STLs/VORON2.4/Electronics_Compartment/DIN_Brackets/skr_mini_e3_bracket_x2.stl

I think the holes are the same between the E3 family so yes, it should be suitable for both, even though I tested it on the E3 Turbo only. I did not find one in the V1 or the usermods repo and after asking on discord no one pointed me to the v2.4 repo, so I designed the above. 
E3 mini is not suitable for a V1 build as it only has 4 drivers but E3 turbo has 5 drivers making a suitable board, especially now that SKR 1.4 is not available and E3 Turbo and SKR2.0 are the obvious alternatives from BTT, so it might be a good idea to add it on the V1 repo for people using the E3 Turbo on a V1 build not to go through the same process I did.

**Comment by KiloQubit** [comment]
Ok, let me know after you print it if it works with the Turbo.  I can't tell from SKR's dimensions in their documentation, because their PDFs don't show enough sizes to fully constrain the holes.

If the mount in the V2 repo does NOT work for your Turbo, then we can merge your mod if you rename it to specify that it's for the Turbo only.

If the mount in the V2 repo DOES work for your Turbo, then I cannot merge this PR, but please open an engineering ticket on Discord and ask for the E3 mount in the V2 repo to also be included in the V1 repo.

**Comment by masimplo** [comment]
Printed it just now. It works the same, so I will just open an issue on the Voron1 repo.

Also here are the positions for the mounts on both boards for future reference:

E3 Mini: 
https://github.com/bigtreetech/BIGTREETECH-SKR-mini-E3/blob/master/hardware/BTT%20SKR%20MINI%20E3%20V2.0/Hardware/BTT%20SKR%20MINI%20E3%20V2.0-SIZE.pdf

E3 Turbo:
https://github.com/bigtreetech/BIGTREETECH-SKR-E3-Turbo/blob/master/Hardware/BTT%20SKR%20E3%20Turbo-SIZE.pdf

**Comment by masimplo** [comment]
Closing this as a similar mount exists on the v2.x repo that can be used for a V1.x build.

**Pull request closed without merging**
