### PR TITLE
V0 Electronics Cooling Fan

### PR DESCRIPTION
**Pull request by rynfox13**
I noticed my V0.1 was getting a few problems with overheating so I decided to do something about it. I made a fan duct using a 24V 3010 blower fan and a small circuit board to control it This seems to work quite well so far in my testing.

I am releasing this modification under GPLv3 in the hopes that it'll help others in the future.

  * [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

* printer_mods/kaze/voron0-pi-fan - A little blower fan (and ducting) to add cooling to the electronics bay of a V0.1.

#### How was it tested? 

It is installed and running on V0.1084, complete with the recommended configuration values.

#### Any background context you want to provide?

This is to hopefully encourage airflow in the electronics bay of the V0.1, as I noticed I was getting temperature warnings in Fluidd.

#### Further notes

This includes a custom circuit board because I could not find extra GPIOs on the MCU. The circuit board can be ordered from JLCPCB complete with the surface-mount components. Unfortunately, this uses EasyEDA for the circuit design, as I could not figure out how to get KiCad to export the BOM and Pick&Place files for the surface mount components.

### CODE REVIEW

**Comment by cbc02009** [comment]
Need to find someone else to validate the gerbers.

**Comment by ademuri** [comment]
FYI, I use KiCAD, and use [this process](https://dubiouscreations.com/2019/10/21/using-kicad-with-jlcpcb-assembly-service/#the_process) to generate the BOM and P&P files for JLC PCB assembly - it works great.

**Comment by rynfox13** [comment]
> FYI, I use KiCAD, and use [this process](https://dubiouscreations.com/2019/10/21/using-kicad-with-jlcpcb-assembly-service/#the_process) to generate the BOM and P&P files for JLC PCB assembly - it works great.

Thanks! I'll check this out in the future!

**Comment by VinnyCordeiro** [comment]
> FYI, I use KiCAD, and use [this process](https://dubiouscreations.com/2019/10/21/using-kicad-with-jlcpcb-assembly-service/#the_process) to generate the BOM and P&P files for JLC PCB assembly - it works great.

Since I've migrated to KiCad 6.0 I started making heavy use of its plugin feature, and I _highly_ recommend this one - https://github.com/Bouni/kicad-jlcpcb-tools - to automatize the production of all the necessary files to order from JLCPCB.

**Comment by rynfox13** [comment]
Good to know. I don't want to go back and redo my PCB files as this one is completely tested and lives on my Voron-0. If I redo them, I'd need to get new PCBs and redo the build.

**Comment by VinnyCordeiro** [comment]
You don't need to redo your PCBs, KiCad 6.0 is backward compatible. However, once you save a project on 6.0, you can't open it anymore on version 5.

**Comment by rynfox13** [comment]
> You don't need to redo your PCBs, KiCad 6.0 is backward compatible. However, once you save a project on 6.0, you can't open it anymore on version 5.

I was meaning the EasyEDA PCB code in this PR. I don't want to redo the work in KiCAD when it was done and works from EasyEDA.

**Comment by VinnyCordeiro** [comment]
> > You don't need to redo your PCBs, KiCad 6.0 is backward compatible. However, once you save a project on 6.0, you can't open it anymore on version 5.
> 
> I was meaning the EasyEDA PCB code in this PR. I don't want to redo the work in KiCAD when it was done and works from EasyEDA.

Oh, my bad. (There's a github repo with code for an EasyEDA to KiCad conversion, but it only works with the PCB, it does not translates the schematics, so I find it less useful.)

**Comment by jlas1** [comment]
The only issue i can see on the STL's is the fan_housing.stl touching the bed with a curved surface, should be changed to make sure that there is no angle lower than 45 degrees touching the bed.
image

**Comment by FHeilmann** [comment]
Since there was no response to the reviewers requests for quite some time, I'm closing this as stale for now.

**Comment by rynfox13** [comment]
Sorry! Life happened and I completely forgot about this. I'll make the fixes probably tomorrow and make a new PR.

**Pull request closed without merging**
