### PR TITLE
Voron0-Mod by JNP

### PR DESCRIPTION
**Pull request by JNP-1**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

### CODE REVIEW

**Comment by JNP-1** [comment]
the complete Mod was tested on my on Voron0 printer

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi, thanks for your submissions. A few comments:

- Please remove the files from the upper level of your mod folder (`printer_mods/JNP/`) 
- Your image folders contain many duplicates (I suspect that all the IMG_####.jpg files are actually duplicates). Please remove the duplicate files.
  - The overhangs on the outer edges of `printer_mods/JNP/Drawer/STLs/Drawer_A.stl`, `printer_mods/JNP/Drawer/STLs/Drawer_B.stl` and `printer_mods/JNP/Drawer/STLs/Drawer_D.stl` are VERY steep. Would it be possible to reduce the angle a bit here?
- Some of your file names have spaces in them. Please remove them.
- Your disclaimer could be merged with your Readme since it's unlikely someone will click on this file with the Readme present
- Regarding your PCBs, we have another repository that is more geared towards PCB projects (VoronDesign/VoronHardware). Would you be open to incorporating your PCB mods (mount STLs included) in that repository instead?

Bests,
-Florian

**Comment by JNP-1** [comment]
Changes made

**Review by john-- — APPROVED** [review]

**Comment by john--** [comment]
Hi,
I've resolved some conflicts in your PR, but I think the PCBs are no longer relevant since you've submitted them to the Voron-Hardware repo like Florian asked. Would you be able to remove the PCBs from this PR so we can finally get it through? Thanks, and sorry for the delay

**Review by FHeilmann — APPROVED** [review]

**Comment by neocats2001** [comment]
Hello,

can someone tell me what is the electronics of this version?

Or put a place to this configuration?

thank you in advance
Drawer

**Comment by JNP-1** [comment]
The electronics I use for this are located here:
https://github.com/VoronDesign/Voron-Hardware/tree/master/V0_PCB_Mod

**Comment by neocats2001** [comment]
are you sure ? i don't find the screen model

**Comment by JNP-1** [comment]
see: 
https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/JNP

**Comment by neocats2001** [comment]
yes ok, thanks a lot. i anderstand. (i'am rookie here)

Last question : what is the firmware ?

**Comment by JNP-1** [comment]
I use Klipper.
At the picture you can see the Repetier-Server UI.
But now I use Klipperscreen instead of Repetier

**Comment by neocats2001** [comment]
ok, thanks you for your help.

**Comment by JNP-1** [comment]
You are welcome

**Comment by neocats2001** [comment]
so a raspberry is necessary ?

**Comment by JNP-1** [comment]
Correct

**Comment by neocats2001** [comment]
ok i anderstand all 

let's go :)

**Pull request merged**
