### PR TITLE
CR10_CR10s_Switchwire_Mod

### PR DESCRIPTION
**Pull request by Soccom1**
* [X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X] Submitted STL files are oriented and scaled properly for printing.
  * [X] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
A new Switchwire mod from a CR10/CR10s
#### How was it tested? 
Test is currently 50% complete on my personal CR10s printer
#### Any background context you want to provide?
My mod is heavily based on Triano's E3P conversion to Switchwire (#232) in theory my mod should work without critical/major issues since I'm using mods previously tested/proved
#### Screenshots (if appropriate)
image
image
image
image
image

#### Further notes
Currently working in Readme and BOM, will update as soon as they are available.

[Soccom_SW_CR10.zip](https://github.com/VoronDesign/VoronUsers/files/6098328/Soccom_SW_CR10.zip)

### CODE REVIEW

**Comment by Soccom1** [comment]
[Soccom_SW_CR10.zip](https://github.com/VoronDesign/VoronUsers/files/6098321/Soccom_SW_CR10.zip)

**Review by KiloQubit — COMMENTED** [review]
It looks like you're still working on this PR, so I've labeled it as draft - since the only file in this PR is the README.  Also, you noted that you've 50% tested this and that it should work in theory - mods will need to be completely tested by you or other Voron users before they can be merged.

**Comment by darkoperator** [comment]
I have a CR-10S I can o the conversion on, what parts have you not tested to validate?

**Comment by KiloQubit** [comment]
@Soccom1 do you plan to update this PR with files in the correct locations so that it can be reviewed?  All you have is a README right now.

**Comment by KiloQubit** [comment]
Closing due to lack of response from author.

**Comment by alegiuk** [comment]
can i have step file?

**Pull request closed without merging**
