### PR TITLE
Add Electronics Bay and Enclosure Seperator for V0, And printer.cfg improvements.

### PR DESCRIPTION
**Pull request by weaslus**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
electronics bay and enclosure seperator. Printer.cfg for klipper in firmware configurations.
#### How was it tested? 
STL. uhhh... not thuroughly tested. i have no chamber thermistor. but prints print. design is very similar to others. If you want more hours printing before merging i am happy to. other users have also already experessed interest so i'm hoping to get them to test. Been about 12 hours printing so far with good results.
Printer.cfg i have run myself for the duration of my printer. maybe 100hrs.
#### Any background context you want to provide?
I had worked on a similar part before. Mak has made a PR for an item i sent him originally and he modified. This is a significant redesign, being removeable and not requireing VHB take but 2 bolts instead. Same outcome.
#### Screenshots (if appropriate)
image submitted in PR for enclosure plate. please have a look!
#### Further notes
Thanks for reading this far.

### CODE REVIEW

**Comment by FHeilmann** [comment]
Hi,
before I go into reviewing this PR in detail, here are two things that jump out immediately:

- It seems somehow an additional `printer.cfg` was added to the changes, that was not intended to be added. Please remove it
- Mods should go into a subfolder under your name, this makes adding further mods easier down the line. Please move the files accordingly.

I'll get back to you about the remaining review.

-Florian

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi,
before I go into reviewing this PR in detail, here are two things that jump out immediately:

- It seems somehow an additional `Printer.cfg` was added to the changes, that was not intended to be added (it's currently at the root of this repository). Please remove it
- Mods should go into a subfolder under your name, this makes adding further mods easier down the line. Please move the files accordingly.

I'll get back to you about the remaining review.

-Florian

**Comment by weaslus** [comment]
Right-O! I moved the STL in printer mods into a further subfolder. and removed the firmware configuration from the pull request. Got too much work to do on that, some feedback has been given already. I will submit that as a seperate PR later if it's not something i feel like submitting as a PR to the main V0 repo.

So hopefully it now matches the recommended format anyhow.
thanks for your time.

**Review by raymondh2 — CHANGES_REQUESTED** [review]
Remove STL and PNG from root of repo

**Review by raymondh2 — APPROVED** [review]

**Pull request merged**
