### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by doubletrouble023**
Holders for LED strips (10mm wide)
V2.4 ( 300 )
Step files are included for those who may wish to make them 50mm shorter/longer so they fit other sizes as well

  * [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

### CODE REVIEW

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi,
thanks for your submission.

- Mods must be added to the top level readme at `printer_mods/Readme.md` Please add your mod there in correct alphabetical order.
- Further, mods must be organized in subfolders in the style of `name_of_submitter/mod_name`. Please move your files accordingly.
- Finally the check list in the PR text was added so you could fill it out and provide necessary info. Please do so. 

Best regards,

-Florian

**Comment by doubletrouble023** [comment]
Hi
Thanks, but you/we really should get a better platform than github for
uploading mods.
It's way to complicated. I've watched the video and made several attempts but
I still don't get it.

Sadly I feel that it's just not worth it for me trying to share stuff this
way


Regards
Victor

ons 30 sep. 2020 kl. 00:05 skrev Florian Heilmann <notifications@github.com

**Comment by FHeilmann** [comment]
Feel free to ping me on discord and I'll gladly help you out. I/We know that github isn't perfect but it wasn't blindly chosen so that's what we are rolling with. 

-Florian

**Review by raymondh2 — CHANGES_REQUESTED** [review]
Please move mods to own folder as per repo guidelines

**Comment by FHeilmann** [comment]
@doubletrouble023 do you intend to further update this PR or does your last commit mean you don't want to pursue this further?

**Comment by doubletrouble023** [comment]
Hi, sorry
No and i dont know how to delete it either...

V

tis 13 okt. 2020 kl. 09:05 skrev Florian Heilmann <notifications@github.com

**Comment by FHeilmann** [comment]
No worries, I will close the PR, requiring no further action from your side. Sorry this didn't work out so well.

Florian

**Comment by doubletrouble023** [comment]
Thx mate


tis 13 okt. 2020 kl. 09:09 skrev Florian Heilmann <notifications@github.com

**Pull request closed without merging**
