### PR TITLE
The bad breath

### PR DESCRIPTION
**Pull request by akhamar**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folder and file naming:
    * Folders and filenames shouldn't contain spaces. Only letters `a-zA-Z`, numbers `0-9`, underscores `_`, hyphens `-` and periods `.`
    * Primary color: `part_xyz.stl`
    * Accent color: `[a]_part_xyz.stl`
    * Opaque color (Blocks light): `[o]_part_xyz.stl`
    * Clear/transparent color (Allows light): `[c]_part_xyz.stl`
    * Quantity, if more than one is needed: `part_xyz_x4.stl`
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

The bad breath: an air filter that anchor at the top of a printer and that can be chained with multiple bad breath.

#### How was it tested?

On my main printer.

#### Any background context you want to provide?

Printed nevermore V5. The LID got warped by the temps and the airflow ain't great. Decided to do my own design.

#### Screenshots (if appropriate)

Image folder.

#### Further notes

N/A

### CODE REVIEW

**Comment by MapleLeafMakers** [comment]
Thanks for splitting up the PRs!  This one looks pretty good, but CAD Sources are missing.

**Comment by akhamar** [comment]
> Thanks for splitting up the PRs! This one looks pretty good, but CAD Sources are missing.
I can easily provide a STEP file. But since I'm still doing some minor modification, I would have to multiple time edit it (it's for a larger version and not for the current medium version).
Either I can provide a STEP with partial completion on the large version but will full medium parts, or just delay a bit until le larger version is also released.
What do you recon ?

**Comment by MapleLeafMakers** [comment]
@akhamar if you're using fusion360 you can just hide the components you don't want included before exporting the step file.   The step file should contain the complete and current sources for every stl in the pull request, and not half-finished/unreleased parts.

**Comment by akhamar** [comment]
> @akhamar if you're using fusion360 you can just hide the components you don't want included before exporting the step file. The step file should contain the complete and current sources for every stl in the pull request, and not half-finished/unreleased parts.

Oh ! Didn't knew you could do that with fusion 360

**Comment by akhamar** [comment]
Just updated with CAD file

**Comment by akhamar** [comment]
Currently Receive the PCB and using two bad breath in series. Working like a charm !

**Comment by akhamar** [comment]
Everything is available in the PR... It should be okey for next step.

**Review by cbc02009 — CHANGES_REQUESTED** [review]
The countersinks in all parts facing the plate should either have a chamfer or use the prusa bridging method to make them more printable for people who don't have their printers all the way tuned yet. https://github.com/VoronDesign/VoronUsers/blob/e149af06446fa8376c1f85126a54de5eca9be522/printer_mods/Mastah/the_bad_breath/stl/%5Ba%5D_the_leg.stl is the only part I saw, but if you could fix any countersinks this looks good to me.

**Comment by akhamar** [comment]
As stated in those two PR (https://github.com/VoronDesign/VoronUsers/pull/825 and https://github.com/VoronDesign/VoronUsers/pull/810), you don't need to make chamfer to been able to print.
You need to update your Ellis profile with the latest update. CF: https://github.com/AndrewEllis93/Ellis-PIF-Profile#advanced-bridging-over-holes-sacrificial-bridges

I won't update the STL since the supposed issue is solved by the actual thing that should solve the issue aka the slicer.

**Comment by eddietheengineer** [comment]
> As stated in those two PR (#825 and #810), you don't need to make chamfer to been able to print. You need to update your Ellis profile with the latest update. CF: https://github.com/AndrewEllis93/Ellis-PIF-Profile#advanced-bridging-over-holes-sacrificial-bridges
> 
> I won't update the STL since the supposed issue is solved by the actual thing that should solve the issue aka the slicer.

Hello @akhamar! While I understand your point of view, STLs in the VoronUsers github repository are required to be printable with any slicer the user wants to use, not just a specific slicer with a specific feature enabled. If you can make the fix that @cbc02009 requested to help us out that would be great!

**Comment by akhamar** [comment]
Done

**Comment by MapleLeafMakers** [comment]
@akhamar I don't think this really addresses the problem.  It's not "just" superslicer vs poor slicers, it's that one specific setting that needs to be enabled... Please submit only 1 version that is printable with any slicer.  There is no need for a special version just for the screw hole bridging.

**Comment by akhamar** [comment]
Well it's mainly a mod I made for myself, that have each part I can print perfectly. I don't want to drop those parts just because some settings can't print them.
I can put two piece the one I designed and work properly and one that will work for anyone.

You can chose to not merge my part during the merge request but I won't remove it from my repo.

If needed I can design what part it is.

**Comment by FHeilmann** [comment]
Hi, 

I want to thank you for your submission and want to personally apologize that your submission has not gotten the review it deserves.
We are in the process to restructure the repo to streamline reviews and hopefully solve this issue in the future.

Unfortunately, this means that we will require you to resubmit the mod under the new system.

Please check [here](https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul) for details and instructions on how to proceed. 
If you have any questions, please reach out in the #voronuser_mods channel on the VoronDesign discord.
If you have since moved on from this mod and don't want to resubmit, no further action is necessary from your side.

Bests,

Florian a.k.a. Haribro

**Pull request closed without merging**
