### PR TITLE
Mantis Dual 5015 - Usermods, More Hotend support(Mosquito, Rapido, Crazy Volcano), Redo Documentation, plus more.

### PR DESCRIPTION
**Pull request by mandryd**
* [ x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x ] Submitted STL files are oriented and scaled properly for printing.
  * [x ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Continuation of Mantis mod.  Adds new hotend support.  Adds Mantis usermods.  Updates and general improvements.
#### How was it tested? 
Crazy volcano and rapido support tested by myself.  Mosquito support tested by WingZero.  All the mods in the usermods were tested by the respective user.  
This is a huge update and I appreciate your work on this.

### CODE REVIEW

**Comment by mandryd** [comment]
ugh, stl corruptions.  I'll fix them.

**Comment by cbc02009** [comment]
Can you move the usermods for the mod into a separate repo and just link to it? Not sure about having mods of a mod.

**Comment by mandryd** [comment]
Does it make a difference that I'm the one making the folders, managing the stls, and making readmes for all the mods?   The users don't have repositories.  I made the usermod folder as a way of giving credit to people who helped made things. 

I can move the files, but certain files like the mosquito mounts id prob need to move back into the main.  Honestly, Mantis has just grown so big and become collaborative so just looking for ways to give credit to people.

**Comment by cbc02009** [comment]
mostly it's just to keep things manageable. I don't know when I'll have time to review a 140 file PR, but without the usermods it would be a lot easier to review. it would also allow you to add mods to your mod without needing to make PRs to this repo, which would save you some effort.

**Comment by mandryd** [comment]
Ok I will work on moving stuff to a separate repository

**Comment by mandryd** [comment]
Ok.  I broke out the usermods to a new repository.  Thanks!

**Review by cbc02009 — APPROVED** [review]

**Pull request merged**
