### PR TITLE
Chamber Temp Sensor Cable Chain Clip & TL Sensor Bracket

### PR DESCRIPTION
**Pull request by stefanpieter**
* [ x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ x] Submitted STL files are oriented and scaled properly for printing.
  * [ x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
A temp sensor bracket to clip onto 10x15 cable chains for chamber readings.

#### How was it tested? 
Yes

#### Screenshots (if appropriate)
Yes

#### Further notes
Step file is provided

### CODE REVIEW

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi, thanks for your submission, I have a few requests:

- You didn't add your mod to the top-level readme at `printer_mods/Readme.md` please add both of your mods to this readme in alphabetical order
- Spaces are not allowed in folder names and, for consistency, should also be removed from file-names. Please change the folder and file names accordingly.
- You provide images with your mod, please include them in the readmes (check how other submissions do this) so users can easily see what your mod looks like.
- Mod submissions need to proved STLs of the mods printable without support and oriented correctly for printing. Please add STLs for your mods.

Bests,
-Florian

**Review by raymondh2 — CHANGES_REQUESTED** [review]
Include STLs for printed parts

**Comment by FHeilmann** [comment]
@stefanpieter do you intend to update this PR to get it merged?

**Comment by stefanpieter** [comment]
Hello Team

I have added the missing STL's and added another mod with all the needed files

**Comment by stefanpieter** [comment]
The file names have been updated and the readme on printer_mods

**Comment by stefanpieter** [comment]
@FHeilmann please can you update the PR :-)

**Comment by FHeilmann** [comment]
Hi @stefanpieter. Unfortunately it looks like some tool added some 400 files to your PR (The `Icon` files). Unfortunately I won't be able to merge the PR this way. Either find a way to remove those extra files or close this PR and create a "fresh" one. 
Let me know if you need any assistance.

Florian

**Comment by KiloQubit** [comment]
@stefanpieter do you intend to fix this pull request to remove extraneous files?

**Comment by KiloQubit** [comment]
Closing due to lack of response from author.

**Pull request closed without merging**
