### PR TITLE
roller brackets for V2

### PR DESCRIPTION
**Pull request by omelethc**
* [x ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ x] Submitted STL files are oriented and scaled properly for printing.
  * [ x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
roller brackets for V2 printer for easy setting printer on its side
#### How was it tested? 
use it myself
#### Any background context you want to provide?
no
#### Screenshots (if appropriate)
included cad image
#### Further notes
none

### CODE REVIEW

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi, thanks for your submission. While the rollers certainly look very nice, their printability needs to be improved in order for this PR to be merged. Maybe you can make the angles a bit more gradual so the overhangs aren't as extreme.

Here's a picture of what the current version looks like in PrusaSlicer. Ideally, all the dark-blue lines should be avoided.

image

-Bests,
Florian

**Comment by omelethc** [comment]
I want to make the changes.  I'm working on it.  It is more effort to figure out how to change them in this god forsaken system than to redo the mod.

**Comment by omelethc** [comment]
I limited the overhangs to this one to 45 degrees and added another part.

**Comment by omelethc** [comment]
I made the requested changes.  Overhangs are 45 degrees now.

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Only one change, please update the image URL in the README.

**Review by KiloQubit — APPROVED** [review]
Thanks, looks good now.

**Comment by KiloQubit** [comment]
@FHeilmann I can't merge this because your review also requested a change and needs to be resolved.  If you can mark it as resolved, I should be able to merge.

**Review by FHeilmann — APPROVED** [review]

**Comment by thenickdude** [comment]
Thanks for this design, they work nicely! But I had to use M3x18 rather than the M3x12 described in the readme.

**Pull request merged**
