### PR TITLE
Update Voron_V0_Parts_Logo.stl

### PR DESCRIPTION
**Pull request by rablaine**
#### Which mods/configurations/profiles are added by this PR?
Not added, just updated existing conqueror433/Voron_V0.1_Parts_Logo

#### How was it tested? 
It's an aesthetic piece with an aesthetic change.  I reprinted and verified it looks right now.

#### Any background context you want to provide?
The gear icon to the top right of the Mini AB looks to be added after the fact (not in the repo pics) and is only 1 layer high instead of 3 like the others.  This is very obvious in the printed piece so I fixed and reprinted it.

#### Screenshots (if appropriate)
Shown in the model viewer:
https://cdn.discordapp.com/attachments/941073225109090374/988906102127198258/unknown.png

How it looked in the prints:
https://cdn.discordapp.com/attachments/941073225109090374/988906238790234152/C540A591-7F9A-4481-83CB-68E5A467E4AC.jpg

The raised gear in my fix:
https://cdn.discordapp.com/attachments/941073225109090374/988910370099982356/unknown.png

And a before and after.  (Before on left, my new version on the right)
https://cdn.discordapp.com/attachments/941073225109090374/988918683168571452/IMG_6315.jpg

### CODE REVIEW

**Comment by Rhastlyn** [comment]
Realize this is a mod of another user's mod; recommend adding a 0.4mm chamfer to the bottom side of the part for printability.

**Comment by cbc02009** [comment]
@rablaine in order to modify other user's mods you need to have them comment in the PR here to approve of the changes.

**Comment by rablaine** [comment]
@conqueror433 I made a small change to the V0 parts model.  Raised the gear to the same height as the other parts and added a .4mm chamfer to the bottom for printability.  Requesting your approval for the changes if you like them.

**Comment by FHeilmann** [comment]
Hi, 

I want to thank you for your submission and want to personally apologize that your submission has not gotten the review it deserves.
We are in the process to restructure the repo to streamline reviews and hopefully solve this issue in the future.

Unfortunately, this means that we will require you to resubmit the mod under the new system.

Please check [here](https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul) for details and instructions on how to proceed. 
If you have any questions, please reach out in the #voronuser_mods channel on the VoronDesign discord.
If you have since moved on from this mod and don't want to resubmit, no further action is necessary from your side.

Bests,

Florian a.k.a. Haribro

**Pull request closed without merging**
