### PR TITLE
Carbon Fiber X Extrusion

### PR DESCRIPTION
**Pull request by aTinyShellScript**
* [ ✔️ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ✔️ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ✔️ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ✔️ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ✔️ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ✔️ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ✔️ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ✔️ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ✔️ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ✔️ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

This PR adds the Carbon Fiber X extrusion replacement mod. It includes tools for holding nuts in place during rail attachment, inserts to replace the tnuts, and modified XYjoints for both stock and pinned idlers.

#### How was it tested? 

This has been tested for 95+ hours on my v2.4. Have had a few Discord users build their own.

#### Any background context you want to provide?

Saw a carbon fiber x extrusion in a Josh Murrah video and couldn't find a mod to do it.

#### Screenshots (if appropriate)

Please see README.md

### CODE REVIEW

**Comment by aTinyShellScript** [comment]
Updated the insert STLs based on feedback from a user who sourced their carbon fiber tube from AliExpress. Also included CAD this time around. Moving from Draft back to Ready for Review.

**Comment by aTinyShellScript** [comment]
This is actually done now, no more updates from me.

**Comment by MapleLeafMakers** [comment]
@aTinyShellScript this looks good to me, but the branch will need to be updated before it can be merged.

**Comment by aTinyShellScript** [comment]
@MapleLeafMakers I just realized you had commented on this. Changes made.

**Comment by FHeilmann** [comment]
Hi, 

I want to thank you for your submission and want to personally apologize that your submission has not gotten the review it deserves.
We are in the process to restructure the repo to streamline reviews and hopefully solve this issue in the future.

Unfortunately, this means that we will require you to resubmit the mod under the new system.

Please check [here](https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul) for details and instructions on how to proceed. 
If you have any questions, please reach out in the #voronuser_mods channel on the VoronDesign discord.
If you have since moved on from this mod and don't want to resubmit, no further action is necessary from your side.

Bests,

Florian a.k.a. Haribro

**Pull request closed without merging**
