### PR TITLE
Voron SW 9mm Belt Mod

### PR DESCRIPTION
**Pull request by consibonsi**
This mod converts the current belt design from 6mm to 9mm belts.

  * [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### How was it tested? 
Tested by myself. Works great! some pictures of the improvement are on Discord

### CODE REVIEW

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for your mod!  It looks mostly good, but:

- Belt_Anchor - STL is upside down, please rotate it to printing orientation
- What holds the front to back panels together, just the tension in the dovetail joints?  Would it be better to screw them together in some way underneath?  that'd also probably prevent the issue of panels curling up

**Comment by consibonsi** [comment]
> Thanks for your mod! It looks mostly good, but:
> 
> * Belt_Anchor - STL is upside down, please rotate it to printing orientation
> * What holds the front to back panels together, just the tension in the dovetail joints?  Would it be better to screw them together in some way underneath?  that'd also probably prevent the issue of panels curling up

Hi,

i changed the orientation of the belt anchor, should be fine now.
Regarding the panels, they are hold by the dovetail joints, right.  The connection is pretty tight. The problem is on the left side, there is the PSU underneath so there is no space for screws or more material. On the right side this would be possible but then the panel will bent up at the front. I printed the panels a few times and the best solution ist to press them directly after printing. When doing this, they work pretty well and are sturdy and flat.

Thanks in advance

**Comment by consibonsi** [comment]
i got a question, how do i change the topic of my mod at the mainpage where all the names are listed? currently there is "consibonsi - Update README.md" :D since i am planning a few more mods for the SW i would like to change that to a more general and not that specific like "SW 9mm Y Mod"

thanks

**Review by KiloQubit — APPROVED** [review]
Thanks for the updates!

**Comment by KiloQubit** [comment]
> i got a question, how do i change the topic of my mod at the mainpage where all the names are listed? currently there is "consibonsi - Update README.md" :D since i am planning a few more mods for the SW i would like to change that to a more general and not that specific like "SW 9mm Y Mod"

You're just seeing the title of your last commit, that's not the "main page where all the names are listed".  The main page where the mods are is https://github.com/VoronDesign/VoronUsers/blob/master/printer_mods/README.md , and you've added your name and mod to it in alphabetical order:

Screen Shot 2021-03-26 at 08 53 51

your mod is called `Y-Mod SW 9mm`, not `Update README.md`.

**Comment by KiloQubit** [comment]
Also, when you do make more mods, make sure you delete your fork of VoronUsers repository, and then fork it again right before you create your pull request, so that your fork is up to date.  Otherwise your current fork will get out of date over time and will be more difficult to merge.

**Pull request merged**
