### PR TITLE
MacNite Mods and RRF3.x for Trident

### PR DESCRIPTION
**Pull request by MacNite**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

### CODE REVIEW

**Comment by MacNite** [comment]
Which mods/configurations/profiles are added by this PR?
Firmware RRF3 for Voron Trident
Printer_Mods: MacNite: Duet 6HC + 3HC Mount, PanelDue 7i Mount, PanelDue5i Mount, FIlament Runout Sensor
How was it tested? Printed and used in my Voron V1.8 and Trident.

**Comment by cbc02009** [comment]
It might be a good idea to separate the mods from the reprap stuff. I could approve the mods, but I don't know enough about reprap to verify that portion.

**Comment by MacNite** [comment]
OK,

Is there any easy way to Split this pull request or do I have to create 2 seperate new ones?

Thanks for your Help,
Max

**Comment by cbc02009** [comment]
I would just create a seperate pull request for the RRF files and modify this to only include the mods, but if it's easier to create two new pull requests you can do that too.

**Comment by newphreak** [comment]
@MacNite can you make the requested changes?

**Comment by MacNite** [comment]
> @MacNite can you make the requested changes?

Sorry, I am Not able to do that because I do not know how to use GitHub for this and do Not have the time to learn IT.

**Comment by cbc02009** [comment]
@MacNite just delete the RRF files from this PR and once it's merged create a new PR with just the RRF files.

**Comment by MacNite** [comment]
> @MacNite just delete the RRF files from this PR and once it's merged create a new PR with just the RRF files.

Ok, I have done this.

**Comment by cbc02009** [comment]
@MacNite the RRF files are still in the PR (look at the Files Changed tab at the top of the page). Did you remember to push the changes to github?

**Comment by FHeilmann** [comment]
@MacNite if you'd still like to submit this mod, please reach out to me (Haribro) on discord. Unfortunately this PR is too far gone to get it into the main repo without tons of work, and it'll be easier if I assist you to start from scratch

**Pull request closed without merging**
