### PR TITLE
Reiten966 mods

### PR DESCRIPTION
**Pull request by Reiten966**

### CODE REVIEW

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for your mod!

- Please remove spaces from your directory name.
- Please add a description of your mod, including the images you added to the `README.md` inside your mod directory.
- Please add a link to your mod in alphabetical order to `printer_mods/README.md`.

**Comment by Reiten966** [comment]
> Thanks for your mod!
> 
> * Please remove spaces from your directory name.
> * Please add a description of your mod, including the images you added to the `README.md` inside your mod directory.
> * Please add a link to your mod in alphabetical order to `printer_mods/README.md`.

Hi, thanks for the comments. How do I add images to README.md?

**Comment by Reiten966** [comment]
> Thanks for your mod!
> 
> * Please remove spaces from your directory name.
> * Please add a description of your mod, including the images you added to the `README.md` inside your mod directory.
> * Please add a link to your mod in alphabetical order to `printer_mods/README.md`.

Also...How do I do this:

> add a link to your mod in alphabetical order to printer_mods/README.md

**Comment by KiloQubit** [comment]
README is in markdown format ( https://guides.github.com/features/mastering-markdown/ ).

To add an image of your mod to your README you'd do something like

    Duct bottom

For `printer_mods/README.md`, there are instructions in there near the top, but if you look at the file it has a table of all the mods in alphabetical order by username.  Add your mod to that table.  Easiest way is to copy an existing row and modify it.

**Comment by KiloQubit** [comment]
@Reiten966 are you still planning to update this PR based on the review?

**Comment by KiloQubit** [comment]
Closing due to lack of response from author.

**Pull request closed without merging**
