### PR TITLE
Voron 2 rgb g code button

### PR DESCRIPTION
**Pull request by Agent-Cain**
#### Which mods/configurations/profiles are added by this PR?
RGB_G-Code_Buttons

#### How was it tested? 
some user already reached out to me and printed theire own ones 

#### Any background context you want to provide?
revised version of meteyous button for legacy printers

#### Further notes
also includes modified skrits to fit more buttons on the 2.4

### CODE REVIEW

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for your mod!

- please move your mod to a subdirectory under your name - instead of `printer_mods/rgb_gcode-button/` it should be in `printer_mods/Agent-Cain/rgb_gcode-button/`
- please modify `printer_mods/README.md` to add a link to your mod in alphanumeric order
- is this overhang at the top more than 45 degrees?  please make sure no overhangs are more than 45 degrees
Screen Shot 2021-04-04 at 16 06 06
- All the skirt STLs in the `standard` directory, and the 250 in the `mod` directory are oriented incorrectly for printing

**Comment by KiloQubit** [comment]
Hi, do you intend to address the review of this PR?

**Comment by Agent-Cain** [comment]
> Hi, do you intend to address the review of this PR?

ABSOLUT ! 
Have worked out a non glued version but it took a few iterations. 
I will have to rework all the button cover also, so it takes a bit of time but I#m on it !

**Comment by KiloQubit** [comment]
@Agent-Cain are you still planning to update this PR?

**Comment by Agent-Cain** [comment]
Yes. 
Everything is almost done and most of the parts are already tested by different people. 
Should be done by the end of the week.

**Comment by bdbell** [comment]
Been a bit, any updates?

**Comment by Agent-Cain** [comment]
> Been a bit, any updates?

I have redone all stls. 
Let me find out how to proper adress all your request  :D 

Thanks for keeping the standard high :)

**Comment by Agent-Cain** [comment]
Is there anything still wrong or is this PR just unreviewed ?

**Comment by MapleLeafMakers** [comment]
@Agent-Cain the mod still includes many glue-on parts.  as stated by KiloQubit, mods cannot require glue. please remove the glue-on parts and instructions if you want to have this mod merged.

Since this mod was created, V2.4r2 was released with some changes to the skirt design.  If this mod isn't compatible please update the readme to state that it is only compatible with r1.

At least one of the skirt STL's isn't oriented correctly for printing: `skirt/mod/front_rear_skirt_a_250_agent_mod.stl`  I did not check all the STL's only a few.

The PR itself has gotten very outdated, please merge the latest upstream changes so that this can be cleanly merged.

**Comment by cbc02009** [comment]
Closing due to inactivity.

**Comment by Ramalama2** [comment]
> @Agent-Cain the mod still includes many glue-on parts. as stated by KiloQubit, mods cannot require glue. please remove the glue-on parts and instructions if you want to have this mod merged.
> 
> Since this mod was created, V2.4r2 was released with some changes to the skirt design. If this mod isn't compatible please update the readme to state that it is only compatible with r1.
> 
> At least one of the skirt STL's isn't oriented correctly for printing: `skirt/mod/front_rear_skirt_a_250_agent_mod.stl` I did not check all the STL's only a few.
> 
> The PR itself has gotten very outdated, please merge the latest upstream changes so that this can be cleanly merged.

I don't know if you are stupid and even checked the files.

1. There is nothing with glue on the snapon/pressfit version and it works great.
2. Why is this mod not compatible with 2.4r2? I have it on 2.4r2.... Did the skirts changed, are they not hexagonal anymore?

Next time, test and look into the files before you write your bullshit.
Bye

**Pull request closed without merging**
