### PR TITLE
Smol Stealth Burner

### PR DESCRIPTION
**Pull request by Maverick-3D**
* [ ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ ] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Adding the SSB and removed dated mods of my own design.
#### How was it tested? 
LOTS of printing.

### CODE REVIEW

**Comment by cbc02009** [comment]
Just FYI it looks like you made this PR from your master branch and it deletes some files from your other mods. This is why we recommend making the PR from a branch other than master.

**Comment by Maverick-3D** [comment]
Ah! I was unaware of the branch vs master thing. Regarding the deleted files, that was intentional. They were 14+ months old and much better mods have been released since then. 

Should I resubmit the PR from a branch?

**Comment by cbc02009** [comment]
Since I don't have much time right now to deal with pull requests i would create a new PR from a branch in case you want to do any other mods in the meantime. right now any changes you make to master will show up on this PR. It's up to you though.

**Comment by Maverick-3D** [comment]
Ok cool, thanks for the feedback :)

**Comment by Maverick-3D** [comment]
Closing this PR to resubmit from a branch, as per feedback received.

**Pull request closed without merging**
