### PR TITLE
Voron 1.x/2.x flexi feet 

### PR DESCRIPTION
**Pull request by marcdebruijn**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Flexible foot replacement for the stock rubber compression feet in the Voron BOM.

#### How was it tested? 
Installed on Voron2.4

#### Any background context you want to provide? 
I was getting frustrated with the stock rubber compression feet. They blocked my electronics compartment hinge from being able to function properly. Also, when turning the printer on it's side for maintenance, stock feet kept folding over and getting in the way.

#### Screenshots (if appropriate)
in Images directory.

#### Further notes
This PR seems to supersede PR #625 I submitted on February 14, 2022, I don't think I can split them out without messing up the index contained in printer_mods/README.md.

### CODE REVIEW

**Comment by cbc02009** [comment]
Please split all mods into separate pull requests.

Are these feet compatible with v2.4r2?

**Comment by marcdebruijn** [comment]
> Please split all mods into separate pull requests.
> 
> Are these feet compatible with v2.4r2?

Thanks for that; I'll split them in to two requests. I already have another PR open for the HEPA filter, but I was concerned if I didn't base this PR on that branch that there might be a merge conflict with printer_mods/README.md. I guess we can cross that bridge when we come to it.

Regarding compatibility with 2.4r2, I've just had a look and the feet are rather different, so I'll have to make a separate STL to allow folks to customize r2 feet.

**Comment by cbc02009** [comment]
The flex feet files seem to be missing from the PR now? was that intentional?

**Comment by newphreak** [comment]
@marcdebruijn pingaroo.

**Comment by cbc02009** [comment]
Closing due to inactivity.

**Pull request closed without merging**
