### PR TITLE
Adds ESP32-Cam and Cable Chain Covers

### PR DESCRIPTION
**Pull request by thebelin**
#### Which mods/configurations/profiles are added by this PR?
Two mods are added:
* cable chain clip with logo:  a simple slip replacement for the 10X11 cable chain and 10X15 cable chain as used in Voron Printers.
* esp32-cam case and mount

#### How was it tested?
I've installed both of these mods on my printer.

#### Further notes
Thanks for all your work!

### CODE REVIEW

**Comment by jlas1** [comment]
The cable_chain_logo_cover STL files looks printable, they don't have the 0.4mm chamfer, but there is really no room for it.
The handle also seems very small for me, but i guess that there is not a lot of room to make it bigger.
image

**Review by jlas1 — CHANGES_REQUESTED** [review]
printer_mods/thebelin/cable_chain_logo_cover/IMG_20211019_194857.jpg is a bit unfocused, i would change it.
printer_mods/thebelin/esp32-cam-voron/esp32-cam-FrontV2.stl is with the wrong print orientation, needs to flip on the X or Y axis 180 degrees.
printer_mods/thebelin/esp32-cam-voron/esp32-cam-BaseV2.stl has some export errors 
image

None of the esp32-cam-voron STL files has a 45 degree chamfer everywhere they touch the bed, you need to add it.
There is also some overhangs higher than 45 degrees (lines in blue below), some i believe are avoidable, can you check.
image

**Comment by jlas1** [comment]
Meanwhile, since you created this PR, it is now required to include a CAD file.
"Submission includes a CAD file in the form of a .STEP or .SCAD file"

**Comment by newphreak** [comment]
@thebelin can you make the changes requested?

**Comment by thebelin** [comment]
I used Blender to build these files and don't have SCAD or STEP files to upload.

**Pull request closed without merging**
