### PR TITLE
Pr v0 wagomount

### PR DESCRIPTION
**Pull request by LaKoBlue**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. **Not applicable**
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).** Not applicable **

#### Which mods/configurations/profiles are added by this PR?
Adds a mod (addendum) to the V0 to screw-mount or clip-mount Wago-221 terminals to the 1515 extrusions

#### How was it tested?
Clips were tested by several users with LDO and Makerbeam profiles.

#### Screenshots (if appropriate)
Pictures and usage description were added README.md

### CODE REVIEW

**Comment by LaKoBlue** [comment]
Closed due to unseen errors. Will reopen after fix

**Comment by LaKoBlue** [comment]
Reopened after fix of CAD model

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Can you modify the design so it doesn't require glue? Glue is not used anywhere else in VORONs. You could for example make the clip go through a hole in the other part and then clip into the extrusion, where the clip essentially acts like a screw holding the other piece to the extrusion.

Did not look at files renamed without changes.

Checked:
- mod is in the correct directory
- no spaces in directories
- mod-specific readme is included
- modified top level readme
- STLs are oriented correctly

**Comment by LaKoBlue** [comment]
> Can you modify the design so it doesn't require glue? Glue is not used anywhere else in VORONs. You could for example make the clip go through a hole in the other part and then clip into the extrusion, where the clip essentially acts like a screw holding the other piece to the extrusion.

I tried that but then the snap-ins aren't able to be printed without support. But I have another idea to test...

**Comment by FHeilmann** [comment]
@LaKoBlue I would agree with @KiloQubit that glue is something not really desired in Voron 3D printers and I'd like to uphold this standard for mods. How did your other idea play out?

Bests,

Florian

**Comment by LaKoBlue** [comment]
Updated to use screws now

**Review by FHeilmann — CHANGES_REQUESTED** [review]
HI, thanks for the update. On your pictures the snap-in pieces have holes in them, but the STLs have not. I assume this is an error (If I understand correctly a screw has to go in there)

Unfortunately, a lot of unintended changes also got pulled into your PR (lots of changes in Kruppes' Deck Panel Inserts. Please remove those changes from the PR.

Bests,

Florian

**Comment by LaKoBlue** [comment]
Corrected the screw holes, so far.
Still have to check on the unintended changes...

**Comment by LaKoBlue** [comment]
Will close this PR. Have reopened [PR 211](https://github.com/VoronDesign/VoronUsers/pull/211) without the unintended changes

**Pull request closed without merging**
