### PR TITLE
Decontaminator Purge Bucket

### PR DESCRIPTION
**Pull request by edwardyeeks**
Porting this mod from legacy over to current VoronUsers. Readme has been updated to current VoronUsers.

### CODE REVIEW

**Comment by edwardyeeks** [comment]
After checking V2.4 CAD, the purge bucket design has been tweaked to resolve potential geometry conflicts. Now there is a stop option to help locate the spring steel sheet. Let me know if anything pops up.

Edward

**Comment by edwardyeeks** [comment]
After a little struggle with figuring out relative links, I've done the requested changes. Thanks for reviewing!

Edward

**Comment by FHeilmann** [comment]
Hi, thanks for implementing the changes. However you forgot to remove the mod from the `legacy_printers/printer_mods/Readme.md`. Please do that, and I'll look to merge ASAP

-Florian

**Comment by edwardyeeks** [comment]
Classic error, done!

Edward

**Review by FHeilmann — APPROVED** [review]

**Pull request merged**
