### PR TITLE
Skirts for V2.4

### PR DESCRIPTION
**Pull request by roboticator24**
Blank centre skirt section for "headless" V2.4

### CODE REVIEW

**Comment by roboticator24** [comment]
Added DIN mount with cooling fan for Raspberry Pi mod

**Comment by roboticator24** [comment]
Added side-mount spoolholder mod

**Comment by roboticator24** [comment]
Added LED lighting

**Comment by FHeilmann** [comment]
Unfortunately your master branch seems to have become screwed up. Feel free to ping me on discord to fix this.
My suggestion is to close this PR, start with a fresh master copy from VoronUsers and then add your mods again, submitting a new PR afterwards

-Florian

**Pull request closed without merging**
