### PR TITLE
Installing BetterBootLoader on SKRs

### PR DESCRIPTION
**Pull request by kage-chan**
* [✔️] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [✔️] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [✔️] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [✔️] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [✔️] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [✔️] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * ~~[ ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*~~
  * ~~[ ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*~~
  * ~~[ ] Submitted STL files are oriented and scaled properly for printing.~~
  * [✔️] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
A simple step-by-step guide to install BetterBootLoader to a SKR board to enable Klipper updates on the boards without accessing the sdcards.

#### How was it tested? 
I have installed BetterBootLoader on the SKR boards in my v2 with the outlined steps prior to writing the guide.

#### Any background context you want to provide?
I was unable to find any clear instructions on how to install BetterBootLoader and how to flash Klipper onto the SKR boards through the USB connection, so I decided to write town how I have done it so other people have a reference or starting point.

### CODE REVIEW

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for the write-up.  Just need a couple minor changes.

**Comment by kage-chan** [comment]
Hi,

thanks for the very quick review.
I have corrected the typo and changed the command for the directory listing. I actually wanted -d1 and forgot the asteriks. That way you get each entry inside the folder with the full path, which you can simply copy and paste for the FLASH_DEVICE argument for the flashing process.

**Review by KiloQubit — APPROVED** [review]
Thanks, looks good.

**Review by KiloQubit — APPROVED** [review]
Still looks good after latest changes.

**Comment by kage-chan** [comment]
Hi,

yes, sorry, had to implement a few more changes, since I saw that I forgot to describe one step. Added it and now it should be final. For now...

**Comment by raymondh2** [comment]
This will be a better fit for the in progress Voron Documents repo.

**Comment by FHeilmann** [comment]
As @raymondh2 mentioned this will work nicely in the (hopefully available soon) github based documentation, so I'm going to close this PR for now.

**Pull request closed without merging**
