### PR TITLE
Added drop-in replacement, code optimization, improved setup & assemb…

### PR DESCRIPTION
**Pull request by hymness1**
…ly guides

  * [x ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x ] Submitted STL files are oriented and scaled properly for printing.
  * [x ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Quickdraw probe for VSW

#### How was it tested? 
By me and many others

#### Any background context you want to provide?
Updated some files since original pull request. Seems you wanted me to update with original VoronUsers before doing another pull request, so did it the lazy way (I don't know much about GitHub sorry)

#### Screenshots (if appropriate)
None

#### Further notes
Added drop-in replacement, code optimization, improved setup & assembly guides

### CODE REVIEW

**Comment by cbc02009** [comment]
It might be a good idea to pull the config files out into a separate git repo and just link to it from the readme fie, so that you don't have to make PRs and wait for them to get merged every time you change the config.

**Comment by hymness1** [comment]
Yeah I guess I can be a pain. Sorry about that, and to be honest I'm not
even sure I understand what you mean :P I'll do some research, sorry for
the inconvenience. Have a nice day!

Le mar. 28 déc. 2021, à 16 h 40, cbc02009 ***@***.***> a
écrit :

**Comment by cbc02009** [comment]
No, I was just trying to save you some work. Check out the klicky probe here: https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/JosAr/Klicky-Probe#step-6-klipper-configuration-dockundock-macro . the author keeps the STLs and instructions in the usermods repo, but then points the user to a different repo for the config, so he can update it whenever he wants. I thought this might save you a lot of work.

**Comment by hymness1** [comment]
I wanted to say thanks for your help. I did what you asked me to and did
some changes since last pull request and I think it should be good to go
now.

Do you want me to do another pull request or you'll be able to figure it
out?

If you have any questions please ask. Thanks again!

Le mar. 28 déc. 2021, à 17 h 47, cbc02009 ***@***.***> a
écrit :

**Review by cbc02009 — APPROVED** [review]

**Pull request merged**
