### PR TITLE
New Mods

### PR DESCRIPTION
**Pull request by xbst**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
The list is really long. I was too lazy with PRs :P

New mods to the repo:
V0 Nuttrap Replacement DXF
2020 Top Spool Holder
v0.1 Tall Legs
v0.1 Skirt Buttons
v0.1 Square Tophat

Following mods had minor updates:
Car Hood Style Bed Hinge - Alternate Handle STLs (less flexible, more difficult to use, so old one is included too)
Mobius 4 (M4) V0 Mod - Printability update to the "Motor_Plate.stl" file.

Added pictures to the following mods:
v0.0 Buttons & OLED Mount (listed below for name update too)
Renderd pics added to more old mods initially but changed my mind.

Following mods name was updated from v0 to v0.0 to avoid confusion (not compatible with "recent" v0.1):
V0.0 ADXL345 Mount
V0.0 Buttons & OLED Mount
V0.0 Easy Access Rear Panels
V0.0 Hat LED Mount
V0.0 Electronics Cover

The readme file was updated with the trident checkmarks.

#### How was it tested? 
Multiple mods in this PR. All new mods included and new handle were tested by me and worked well. M4 mod printability update was tested by others on [Discord](https://discord.com/channels/460117602945990666/724085489748934898/795343820652937247).

#### Any background context you want to provide?
No.

#### Screenshots (if appropriate)
No.

#### Further notes
Did my best to make sure everything is correct but there are a lot of mods in this PR. Sorry if I missed something.

### CODE REVIEW

**Comment by xbst** [comment]
Added v0.1 Revo Micro mount. Was tested by me & other beta testers during the beta.

**Comment by xbst** [comment]
Yay!

**Comment by cbc02009** [comment]
Sorry about missing this one for so long. Not sure what happened. Can you possibly break this up into smaller pull requests, just for my own sanity? Maybe one or two mods per PR max?

**Comment by xbst** [comment]
I'm a GitHub noob still. Took me a while to figure out how to delete an old repo and fork again for new PRs (which is why there are this many mods in this PR). I don't think I can create multiple banches with multiple PRs yet.

**Comment by FHeilmann** [comment]
Hi, 

I want to thank you for your submission and want to personally apologize that your submission has not gotten the review it deserves.
We are in the process to restructure the repo to streamline reviews and hopefully solve this issue in the future.

Unfortunately, this means that we will require you to resubmit the mod under the new system.

Please check [here](https://github.com/VoronDesign/VoronUsers/wiki/VoronUsers-Overhaul) for details and instructions on how to proceed. 
If you have any questions, please reach out in the #voronuser_mods channel on the VoronDesign discord.
If you have since moved on from this mod and don't want to resubmit, no further action is necessary from your side.

Bests,

Florian a.k.a. Haribro

**Pull request closed without merging**
