### PR TITLE
Add Ender 3 and 3 Pro Switchwire Mod

### PR DESCRIPTION
**Pull request by Gizzzle**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Ender 3 and 3 Pro Switchwire Mod
#### How was it tested? 
Build by me and RCF
#### Any background context you want to provide?
Entry way to get the Voron feeling
#### Screenshots (if appropriate)
In the readme

### CODE REVIEW

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi, 
thanks for the submission. However many files are not oriented correctly and on some I'm not sure they will be printable without support at all. Until those are fixed I'm afraid this PR cannot be merged.

Bests,
-Florian

**Comment by Gizzzle** [comment]
Hello there, the parts are now reuploaded with a correct orientation.

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Thanks for the update, 
I looked at the STLs and have two comments:

- `LRS-350-24_PSU-Cover_x1.stl` does not meet the printability standards of this repo, as it requires supports to prop up the "ceiling" of this cover. I'm afraid you'll have to find a way to change the design so it can be printed without supports.
- `[a]_Belt-Clip_x2.stl` has this weird pattern around the screw hole:
image
is that intended? Otherwise I guess this STL needs to be re-exported.

Otherwise the mod looks good to me.

-Florian

**Comment by Gizzzle** [comment]
Seems that Fusion exported the belt clip with the insert, sorry for that. I'm currently in touch with RCF regarding the PSU, but I believe he said he printed everything without supports. Will report back later and request a new review.

**Comment by russiancatfood** [comment]
@FHeilmann Unfortunately in this particular case PSU cover has to be printed this way. At least that's how I designed it.

**Comment by turbotrix** [comment]
Hi Gizzle  you mention Advanced version of your Mod with grills,can you point me in right direction?

**Comment by ChaosBlades** [comment]
These are the issues I have found just looking at the CAD and printing the LCD parts.

1. Ender 3 Pro variants of parts are not included in the CAD. **I need these do you have them?**
2. The connectors for the Ender 3 Pro display are at the very top of the PCB so this back panel does not fit.
3. The dial nob hole is way to small to fit over the nub. So much so this is definitely not a printer/slicer calibration issue.
4. Back panel of LCD cover does not come close clearing the buzzer.
5. LCD mounting holes are completely useless... Looks like the dimensions used for the back panel are the same as the ones used for the front panel where the screws are supposed to screw into. These should be nutserts...
    - Too big for M3 self tapping
    - Too small for M3 nutsert
    - Too small for M4 screws
6. The printer will not sit flat without designing feet for it. Electronics case covers 1 of the original foot locations. At the very least the Electronics Case will need one small section removed to allow for the original feet to be used without removal and awkward positioning of 1 of the feet.
7. I do not think the frame cutout for the wires is going to be cut accurately enough for the Electronics case to be designed the way it is.
8. This design could use the Motor mounts and X carrage mounts from the other [E3P Switchwire Mod](https://github.com/VoronDesign/VoronUsers/tree/master/printer_mods/Triano/Ender_3Pro_Switchwire) to allow for belt tightening and 300mm X rail.
9. Looks like all custom parts use self tapping holes. There should all be converted to nutserts.

It is pretty clear to me this was designed off the Creality provided Ender 3 CAD and not actually printed and tested. All kinds of little quarks and errors are presenting themselves when actually printing the parts. I would like to clean this up and work to actually build a complete Ender 3 Pro physically and in CAD but I will need the missing CAD files to do so.

**Comment by Gizzzle** [comment]
I did indeed use this on my Ender 3 Pro for a long time before abandon it because of a bad frame.
Regarding the issue with the Display and electronics stuff: These were the parts RCF worked on. He also used the parts on his Ender 3. I went not that way since I wanted to make the printer fully enclosed. But I stopped the project so there are no more CAD Files.

Regarding the self tapping holes: The parts worked just fine. As I remember correctly only M5 screws were screwed into plastic which was quiet strong.

**Comment by ChaosBlades** [comment]
I converted everything over to an Ender 3 Pro frame with the proper LCD panel the Pro has. You can see in the CAD all the issues I pointed out. It will not upload the .zip so I put it on mega. Also another issue, the Keyback mount collides with the Z chain. 
https://mega.nz/file/2VNmWJRB#3LwN_sz9zNfwOxM4ezN6VJciLWwL4O8pO93VdsMavT0

The Ender 3 Pro you and RCF used had to be a super early sample or something weird going on. I have been making mods for Ender 3 Pros for 2 years and from my experience they are the same as what I have. I have made nobs and back panels for the LCD specifically and I have had no complaints from anyone that has downloaded them to install on a Pro.

It really sucks you don't have the original Pro versions of the files. I guess I will need to re-build them from scratch.

**Pull request merged**
