### PR TITLE
Voron V0 LCD Touchscreen Skirt

### PR DESCRIPTION
**Pull request by jgehrig**
***WORK IN PROGRESS***

CAD_Main_Assembly

## Description
This is a 3.2" color LCD touchscreen mount for the Voron V0 skirt. Designed for use with [OctoScreen](https://github.com/Z-Bolt/OctoScreen).

The design adds a 40mm high skirt for extra clearance in the bottom electronics bay, and to better fit the large touchscreen.

Everything was designed to work with the stock mounting points: 4 T-nuts on the front and side Makerbeam extrusions.

## Work Remaining
 - [x] README complete
 - [x]  CAD files + Fusion360 links
 - [x] BOM supplier links for all parts
 - [x] STLs are oriented for printing
 - [x] STLs print without support 
 - [x] BOM parts listed

### CODE REVIEW

**Comment by jgehrig** [comment]
Posting a PR early, since the design work is mostly finalized... Perhaps someone will find this mod useful.

I still need to clean up some of the STLs, re-orientation needed. Most of the remaining work is README related (CAD files, BOM, Suppliers, etc).

**Comment by KiloQubit** [comment]
@jgehrig are you planning to update this PR to get it ready for review?

**Comment by jgehrig** [comment]
@KiloQubit

Yes, I will update this PR. I was waiting on an overseas hardware order (M2.5 fasteners) to finalize the build and BOM.

I will do a few minor STL modifications (hole sizes, orientation), add pictures, and update the BOM.

**Comment by jgehrig** [comment]
@KiloQubit

Done. This is ready for review.

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for your mod!

Please see some comments below.

**Comment by jgehrig** [comment]
@KiloQubit

Comments addressed:
1. Remove URL query parameter on Amazon link
2. Fix A/B side skirt mix-up.
3. Add F3D + STEP CAD Files from Fusion 360.

Thanks for reviewing this! :)

**Review by KiloQubit — APPROVED** [review]
Thanks for the update!

**Pull request merged**
