### PR TITLE
Add Klipper Expander Board Holder

### PR DESCRIPTION
**Pull request by calini**
#### Which mods/configurations/profiles are added by this PR?

`printer_mods/calini/Klipper_Expansion_Board_holder/`

#### How was it tested? 

A sample was printed and used in my build.

#### Any background context you want to provide?

As the Klipper Expansion Board will end up being mounted in the back of a Voron, I thought it was a good idea to have a similar mount to the rest of the boards in the area; Allows heat set inserts or being VHB-tape'd on.

#### Screenshots (if appropriate)
[IMG_3795](printer_mods/calini/Klipper_Expansion_Board_holder/IMG_3795.jpeg)
[IMG_3796](printer_mods/calini/Klipper_Expansion_Board_holder/IMG_3796.jpeg)
[IMG_3797](printer_mods/calini/Klipper_Expansion_Board_holder/IMG_3797.jpeg)

#### Further notes

### CODE REVIEW

**Comment by bdbell** [comment]
These are the new style DIN clips, the hole pattern is pretty standard across Voron.  https://github.com/VoronDesign/Voron-Trident/blob/main/STLs/ElectronicsBay/pcb_din_clip_v2_x5.stl

**Comment by calini** [comment]
Redid everything, now the threaded inserts should line up perfectly with the DIN clips, including the new version used by Trident.

**Comment by cbc02009** [comment]
@calini @timmit99 should we close this one since it's getting merged into voron hardware instead?

**Comment by timmit99** [comment]
@calini  if you're ok with that, i hate making you jump to a different repo but i think it 
makes the most sense to be there

**Comment by calini** [comment]
That's fine, I'll open a PR on the other one. I updated this one since it was already open and to make sure it's looked at; Feel free to close and I'll open one there.

**Pull request closed without merging**
