### PR TITLE
Wansview Camera Mount

### PR DESCRIPTION
**Pull request by Rhastlyn**
* [x ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x ] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x ] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x ] Submitted STL files are oriented and scaled properly for printing.
  * [x ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
This PR is for for two mods:
1)An STL designed to mount a low-cost camera to the printer's extrusion
2)An STL designed to cover the 60mm controller fans on a 2.4 printer without having to access inside the electronics chassis

#### How was it tested? 
Both designs went through several iterations of printing and testing, the posted STLs was printed using standard Voron settings and is currently being used on my Voron 2.4

#### Any background context you want to provide?
1) Hope to provide an alternative for people to mount cameras that are less costly than the common Logitech cameras with the current price inflation of those devices
2) Wanted to provide an alternate minimal cover that still increases safety and aesthetics

#### Screenshots (if appropriate)
Images include in directory structure and readme file for both modifications

#### Further notes
Installation instructions included in readme file for both modifications

### CODE REVIEW

**Comment by Rhastlyn** [comment]
This is my first PR, apologies in advance if I did anything incorrectly.

**Review by FHeilmann — CHANGES_REQUESTED** [review]
Hi, thank you for your submission. A few comments:

- It looks like you submitted 2 mods (the camera mount and the fan grill cover) but only the camera mount is included in the top level readme. Please add the 2nd mod as well.
- The following files don't really have a purpose and can be removed:
`printer_mods/Rhastlyn/60mmFanCover/STL/README.md`
`printer_mods/Rhastlyn/60mmFanCover/Images/README.md`
`printer_mods/Rhastlyn/WansviewCameraMount/Images/README.md `
`printer_mods/Rhastlyn/WansviewCameraMount/STL/README.md`

Otherwise the PR looks good to me!

-Florian

**Comment by Rhastlyn** [comment]
I believe I have everything up to date as requested including updates to the table in the printer_mods/README.md;

Sorry for the confusion, this was my first time using Git and I didn't realize it would append the second mod I did onto the pull request I submitted for the first one. Any point in the right direction on how to do this better next time would be appreciated!

Thank you!

**Comment by FHeilmann** [comment]
you added your mods to your own `master` branch. The "proper" git workflow is to create a separate branch for each mod, that way one PR per branch can be submitted and since each branch only contains one mod, they will be separate.

**Pull request merged**
