### PR TITLE
Voron 2.4 - 3030 profiles on main frame - MGN 12 Z axis

### PR DESCRIPTION
**Pull request by sipi-2**
* [ x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ x] Submitted STL files are oriented and scaled properly for printing.
  * [ x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Voron 2.4 - 3030 profiles on main frame - MGN 12 Z axis
#### How was it tested? 
I made one
#### Any background context you want to provide?
no
#### Screenshots (if appropriate)
yes
#### Further notes
no

### CODE REVIEW

**Comment by sipi-2** [comment]
I uploaded STL files with correct orientation and without spaces. Hope it will be fine. I can't see difference in STL directory, but files were uploaded.

**Comment by sipi-2** [comment]
Hello, what I should do for moving things forward? I uploaded repaired STLs... Thanks

**Comment by KiloQubit** [comment]
> Hello, what I should do for moving things forward? I uploaded repaired STLs... Thanks

Nothing, just wait until one of the maintainers has free time to review the mod.

**Comment by KiloQubit** [comment]
BTW, 2 of your STLs are corrupted, please fix:

    Validating STL printer_mods/sipi-2/STL/Z_Motor_Mount_3030_Left.stl
    !! Detected "Facets added" value of 1
    Validating STL printer_mods/sipi-2/STL/Z_Motor_Mount_3030_Right.stl
    !! Detected "Edges fixed" value of 2

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for your mod!  Please see requested changes below.

- Please create a directory under `printer_mods/sipi-2` for your mod and move your mod there, in case you have other mods in the future - e.g. `printer_mods/sipi-2/voron2_3030`.
- Please modify `printer_mods/README.md` to add your mod in alphabetical order
- You have 8 pictures in the Pictures directory, but only 2 of them are included in the README - please add the other pictures to the README as well
- for all STLs  that need to be printed more than once (e.g. Z bearing blocks) update the filename to add how many copies are needed, e.g. `some_part_x4.stl`
- `Base_plate_3030_{Left,Right}.stl` are upside down
- `Middle_Fan_Support_3030.stl` needs a chamfer in the circled area to avoid printing in air 
Screen Shot 2021-05-01 at 11 13 47

- `Z_Bearing_Block_Top_3030{,_HAL}.stl` - add instructions to punch or drill through the built-in bridge under the hex nut
- `Z_Idler_tensioner_{M3,M4}_3030_bracket_{Left,Right}.stl` (all 4 files) - add instructions to remove built-in support and punch/drill the built-in bridge for the hex nut
- `Z_Motor_Mount_3030_Left.stl` and `Z_Motor_Mount_3030_Right.stl` are corrupted and need to be fixed
- `Z_drive_3030_main {Left,Right}.stl` - remove space from filenames and add instructions to punch/drill the 6 holes with built-in bridges
- `Z_drive_3030_retainer_{Left,Right}.stl` - add instructions to punch/drill the 6 holes with built-in bridges, and notch overhangs are too steep in the circled area, make sure all overhangs are no steeper than 25 degrees:

Screen Shot 2021-05-01 at 11 39 15

**Comment by KiloQubit** [comment]
@sipi-2 do you plan to make the changes requested by this review?

**Comment by KiloQubit** [comment]
Closing due to lack of response from author.

**Pull request closed without merging**
