### PR TITLE
Added new user and mod for a door activated light switch

### PR DESCRIPTION
**Pull request by Sjack1209**
### Which mods are added by this PR? 
Voron_Fridge_Door_Light_Switch

### How was it tested? 
I have it in use on my printer with no issues. I took it through several iterations before uploading it.

### Any background context you want to provide?
I wanted a way to make my white LED's go to full brightness when the door is opened since I usually keep them around 10% in the software. This mod allows you to install a microswitch that accomplishes that. 

### ⚠️⚠️**PLEASE READ AND COMPLETE THE CHECKLIST BELOW**⚠️⚠️

  * [X ] I have read the rules available [here](https://github.com/VoronDesign/VoronUsers/wiki/Mod-Submission-Rules) and
        my mod adheres to these rules.
  * [ X] This mod was created by myself and I agree to publish it under the repository
        [license](https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md)

### CODE REVIEW

**Comment by jontek2** [comment]
Thanks for submitting your mod. Please check the results from the bot above and correct the issues it has mentioned.

I also noticed that the README contains "(Link to Amazon)" and "(Link to Aliexpress)" without any actual links. It's probably best to remove these as well.

**Comment by Sjack1209** [comment]
This is going to fail again.  I think I figured out why it wasn't working....Is it case sensitive when writing file paths?  If so, I've corrected it and will re-submit again once the prior request is completed.

**Comment by jontek2** [comment]
It appears there are inconsistencies between the naming of the image folder and files in the YAML file and the actual image folder.

**Comment by chirpy2605** [comment]
Closing this due to lack of response. If you still want to issue this PR, please resubmit with the requested changes.

**Pull request closed without merging**
