### PR TITLE
Add DIN rail bracket for OrangePi 3 LTS

### PR DESCRIPTION
**Pull request by ameyp**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?

This PR adds a DIN bracket for the OrangePi 3 LTS board. The mounting holes are different from those for Raspberry Pi 3/3b/4

#### How was it tested? 

I printed it and verified that:
1. I can attach it to the Raspberry Pi DIN mount using self-tapping M2x10 bolts.
2. I can attach an OrangePi 3 LTS to it using self-tapping M2x10 bolts.

### CODE REVIEW

**Comment by cbc02009** [comment]
don't add until after #731 merged.

**Review by cbc02009 — APPROVED** [review]

**Comment by cbc02009** [comment]
looks like there are some merge conflicts in the main readme.md file, since I had to rearrange some names to fix some stuff. if you don't know how to fix it I think I can do it from the PR.

**Comment by ameyp** [comment]
I’ll update it

**Comment by ameyp** [comment]
Resolved the merge conflict.

**Comment by JeremyRuhland** [comment]
A couple issues I noticed after printing this mod:

* Counterbores should be on top side of the part, not on the mating surface to the DIN clip.
* Dimensions of this mod are for the orangepi 3, not the 3 LTS. Distance between mounting holes needs to be increased to 79mm on the long axis.

**Pull request merged**
