### PR TITLE
Smootbrain door latch v0.1

### PR DESCRIPTION
**Pull request by chestwood96**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
v0.1 door latch modified to be taped instead of screwed

#### How was it tested? 
Currently on my v0.1 (V0.866)

### CODE REVIEW

**Comment by bdbell** [comment]
Thanks for your mod!

Couple of small things.

1. In your submission to the readme, can you please add ':x: |' to the end so that there are 5 total columns?
2. Are these notches intended? 
image

**Comment by chestwood96** [comment]
Thanks for the review

1. Done
2. I am not sure, that is also on the stock one from the step file. I don't like it but don't have the skills to deal with complex curved stuff in cad
3. Those were not a problem, they actually help holding on to the magnets. I could put it on it's back but that would create pretty steep overhangs that are actually visible which is worse imo so I prefer the way it already is.
image

**Comment by cbc02009** [comment]
can you fix the orientation of this so the flat side is facing down?

**Comment by chestwood96** [comment]
> can you fix the orientation of this so the flat side is facing down?

That would require supports or what flat side do you mean?

**Comment by cbc02009** [comment]
Sorry, I missed some of the conversation I think. Can you post some pictures of how they print in the orientation you've specified? it might help convince some of the other admins that the printability is fine.

**Comment by chestwood96** [comment]
Please ignore the bad first layer quality I didn't clean the bed. The overhangs don't look great but they are ok and the magnets fit with a bit of a push.
image
image

**Comment by chestwood96** [comment]
@cbc02009 @bdbell 
Can I get a yes or no on this, I accidentally did that in main and it is kind of preventing me from submitting some other mods. While I do like having a reason to procrastinate on that I should probably get on with it at some point.

**Comment by cbc02009** [comment]
@chestwood96 go ahead and re-make the PR in a new branch if it's blocking you. I have a feeling there's going to be merge conflicts anyway, so it might be easiest.

Sorry for the delayed response. been pretty busy lately.

**Pull request closed without merging**
