### PR TITLE
IKEA Dioder LED Strip mount

### PR DESCRIPTION
**Pull request by simenon**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
A mount for LED Dioder LED Strip sold by IKEA

#### How was it tested? 
Printed and mounted in a Voron 2.2

#### Any background context you want to provide?
The mounts in the legacy foler by randommen didn't fit the metal brackets. I wanted the LED shining more inwards, and i wanted the metal strips to be mounted with a m3x8 instead of VHB tape

#### Screenshots (if appropriate)
In the folder

### CODE REVIEW

**Review by KiloQubit — CHANGES_REQUESTED** [review]
Thanks for your mod.  Everything looks great, except for consistency with other mods, can you rename your `readme.md` to `README.md`?

Checked:
- mod in correct directory
- no spaces in directory names
- there's a readme for the mod
- top level readme is updated
- STL is oriented correctly and doesn't require supports

**Comment by simenon** [comment]
> Thanks for your mod. Everything looks great, except for consistency with other mods, can you rename your `readme.md` to `README.md`?

File renamed !

**Review by KiloQubit — APPROVED** [review]
Awesome, looks good!

**Review by KiloQubit — APPROVED** [review]
For the M4 jig mod, everything looks good.

Checked:
- mod is in the correct directory
- no spaces in directory or file names
- mod has a README
- top level README modified
- STL in correct orientation and doesn't require support

**Comment by simenon** [comment]
Oops accidentally added a few files in the wrong place, reverted back

**Review by FHeilmann — APPROVED** [review]

**Pull request merged**
