### PR TITLE
DooMini

### PR DESCRIPTION
**Pull request by TigranDesigner**
* [x ] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x ] Folder and file naming:
    * Folders and filenames shouldn't contain spaces. Only letters `a-zA-Z`, numbers `0-9`, underscores `_`, hyphens `-` and periods `.`
    * Primary color: `part_xyz.stl`
    * Accent color: `[a]_part_xyz.stl`
    * Opaque color (Blocks light): `[o]_part_xyz.stl`
    * Clear/transparent color (Allows light): `[c]_part_xyz.stl`
    * Quantity, if more than one is needed: `part_xyz_x4.stl`
  * [ x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ x] Submitted STL files are oriented and scaled properly for printing.
  * [ x] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [ x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### How was it tested? 
Tested by Beta testers from the DoomCube community ( Doom-v0)
At least 4 DooMinis have been printed so far. 

#### Any background context you want to provide?
New enclosure all printed parts.

#### Screenshots (if appropriate)
Manual and photos are included in the repository

### CODE REVIEW

**Comment by bdbell** [comment]
Thanks for your submission. The usable files like STLs, photos, and manual should not be in archive files like rar but should be individually uploaded. The cad files can be archived but should be in a more common format like zip.

**Comment by TigranDesigner** [comment]
Hi

Thank you for taking your time and sending me a reply. Shall I delete and
make a new Branch , or modify the existing one .

Regards
Tigran Kostandyan

**Comment by MapleLeafMakers** [comment]
You can modify the existing branch

**Comment by MapleLeafMakers** [comment]
the DooMini folder needs to be moved inside another folder with your username.

**Comment by MapleLeafMakers** [comment]
There's an extra `ZooMini` folder in printer_mods, along with a duplicate readme.md

**Comment by TigranDesigner** [comment]
Yeah .. that's me being a noob. I will remove that before my next pull
request.

Thank you for your time

Tigran

**Comment by FHeilmann** [comment]
Closing due to lack of activity. It seems resubmitting this PR from scratch is the best course of action.

**Pull request closed without merging**
