### PR TITLE
Handles slim v2

### PR DESCRIPTION
**Pull request by Ch4rlesB**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [x] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
Updated the V0_Handles_Slim stls to V2
#### How was it tested? 
User Feedback
#### Further notes
Added installation instructions and updated the files to V2

### CODE REVIEW

**Review by KiloQubit — COMMENTED** [review]
Thanks for you update!

What changed in version 2?  From a quick glance, I don't see anything obviously different.

Also, if version 2 is better, is there any reason to keep version 1?  It' likely to just confuse users about which one they should print.

**Comment by Ch4rlesB** [comment]
The tang that fits inside the rail was dimensioned for chinesium rails. I had to shorten it down to fit other manufacturers aswell. I would remove V1 if I could but this is how I was instructed to modify an existing mod. Theoretically, its not a V2, its just a fit adjustement

**Comment by KiloQubit** [comment]
> The tang that fits inside the rail was dimensioned for chinesium rails. I had to shorten it down to fit other manufacturers aswell. I would remove V1 if I could but this is how I was instructed to modify an existing mod. Theoretically, its not a V2, its just a fit adjustement

You can definitely modify the existing mod by removing the older files, or replacing them with newer versions, just go to  your branch here https://github.com/Ch4rlesB/VoronUsers/tree/handles-slim-v2/printer_mods/Ch4rlesB/V0_Handles_Slim and make those changes.  I think it's best if you delete the V2 files (confusion with Voron V2), and replace the original files with new versions.

**Comment by Ch4rlesB** [comment]
> > The tang that fits inside the rail was dimensioned for chinesium rails. I had to shorten it down to fit other manufacturers aswell. I would remove V1 if I could but this is how I was instructed to modify an existing mod. Theoretically, its not a V2, its just a fit adjustement
> 
> You can definitely modify the existing mod by removing the older files, or replacing them with newer versions, just go to your branch here https://github.com/Ch4rlesB/VoronUsers/tree/handles-slim-v2/printer_mods/Ch4rlesB/V0_Handles_Slim and make those changes. I think it's best if you delete the V2 files (confusion with Voron V2), and replace the original files with new versions.

Done!

**Review by KiloQubit — APPROVED** [review]
Thanks for the updates!

**Pull request merged**
