### PR TITLE
Mathematical potato

### PR DESCRIPTION
**Pull request by MathematicalPotato**
* [ x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ x] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [ x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [ x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [ x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [ x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [ x] Submitted STL files are oriented and scaled properly for printing.
  * [x ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

### CODE REVIEW

**Review by cbc02009 — APPROVED** [review]

**Comment by cbc02009** [comment]
can you fix the merge conflicts so I can merge this?

**Comment by MathematicalPotato** [comment]
That file was removed previously so I'm not sure why it's causing a conflict

**Comment by cbc02009** [comment]
image

Github still won't let me merge it because of conflicts on this file. Also looks like the CI is stuck and will require another commit to force it to run again.

**Comment by cbc02009** [comment]
let me try and get some help from someone who knows more git than me. it's still not running the CI or allowing the PR.

**Comment by cbc02009** [comment]
Can you just close this PR and make a new one? something really strange is going on.

**Comment by KiloQubit** [comment]
The conflict is because you keep using the same branch in your repository to make different changes.  Your branch diverged from upstream where that file changed in a previous PR, and the history in your branch no longer matches the history in upstream.  I would recommend saving your changes somewhere, and then deleting your fork of VoronUsers and recreating the fork again.  Then for every PR you want to make, create a new branch (**don't keep using the same branch!**), put your changes in that new branch and make a PR from it.  After each PR is merged, you can fast forward your master branch, and then delete your PR branch.

**Comment by MathematicalPotato** [comment]
> 

Thank you, I totally forgot to update my local files with the current upstream master VoronUsers stuff.  My local files look like they updated from upstream and are correct now and it looks like all the checks should be good.  I've been using Git Desktop to do my pull requests and it still looks like it's showing my repository's "master" branch as being 2 months out of date so if it still won't let the pull request be merged I can nuke my fork and try again with a new fork/branches.  I will use that branching method in the future.

**Comment by cbc02009** [comment]
Thanks, Kilo! looks like it's all set now.

**Pull request merged**
