### PR TITLE
Support both SKR 1.3 and 1.4 boards via configurable pin map - NEEDS HELP TESTING!

### PR DESCRIPTION
**Pull request by boardthatpowder**
Dn't merge this just yet.  Needs testing.  But creating to demonstrate an approach for Eddie.

  * [ X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [ X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [ X] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [X ] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [ ] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X ] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X ] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X ] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X ] Submitted STL files are oriented and scaled properly for printing.
  * [ X] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
- Modified Eddie's existing SKR configuration to support both SKR 1.3 and 1.4 boards.

#### How was it tested? 
- Not tested yet, therefore don't merge just yet!  Created the PR for early feedback.

### CODE REVIEW

**Comment by jdlongenecker** [comment]
Hello @boardthatpowder I just wanted to let you know that I haven't forgotten about this work you've done! I'll likely reference it today during the Voron live stream 👍 Once I start generating the V1.8 config files I'll pull your work in and try to update the V2 configs as well, it'll likely be another week or two before I get to it

**Comment by boardthatpowder** [comment]
This is working for SKR1.4, just needs someone to test in SKR1.3.

**Comment by FH3D** [comment]
@boardthatpowder 
i have noticed that you have mapped Pin1.0 as Z-MAX for the SKR 1.4. 
Looking at the 1.4 schematic, there is no internal pullup resistor available on Pin1.0 (all regular endstop pins are equiped with a resistor / 1.3 &1.4)
Maybe this is completely uncritical but i would recommend special attention and testing to ensure the logic states are always right and there is no bouncing.

**Comment by boardthatpowder** [comment]
Thanks for the feedback @FH3D.  You're right, 1.3 endstop MIN/MAX concepts no longer apply to 1.4 even though the physical sockets are located in the same place.  Will revise this approach.

**Comment by boardthatpowder** [comment]
Updated to reflect difference with 1.3 MIN/MAX vs 1.4 STOP endstop pins.

FYI - my own personal config can be found at https://github.com/boardthatpowder/klipper-firmware-voron2 which uses the pin alias concept I backported to here.

**Comment by john--** [comment]
Nice job!

**Comment by boardthatpowder** [comment]
Good catch @john-- I've removed those files.  My mistake.

**Comment by FHeilmann** [comment]
@boardthatpowder any news on this?

**Comment by boardthatpowder** [comment]
> @boardthatpowder any news on this?

I have a variation of this in use with my own SKR 1.4's  (see https://github.com/boardthatpowder/klipper-firmware-voron2).  I don't have a 1.3 to test with.

**Comment by FHeilmann** [comment]
I'll close this PR for now, as it hasn't gotten any attention for quite some time. Feel free to reopen or resubmit once you've found someone to test this PR for you.

**Pull request closed without merging**
