### PR TITLE
MeanWell RS PSU DIN Brackets

### PR DESCRIPTION
**Pull request by aTinyShellScript**
* [X] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [X] Folders names MUST NOT contain spaces. If possible, make sure file names also 
    do not contain any spaces.
  * [X] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [X] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [X] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [X] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [X] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [X] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [X] Submitted STL files are oriented and scaled properly for printing.
  * [X] (N/A) Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

**Which mods/configurations/profiles are added by this PR?**
DIN brackets for Meanwell RS PSUs

**How was it tested?**
Mounted on a DIN rail in my v2.4

**Any background context you want to provide?**
Couldn't find any existing brackets to mount up an RS-150-48.

**Screenshots (if appropriate)**
Images included in Readme.md and/or Images folder.

**Further notes**
n/a

### CODE REVIEW

**Review by cbc02009 — CHANGES_REQUESTED** [review]
Please remove all spaces from filenames

**Comment by aTinyShellScript** [comment]
> Please remove all spaces from filenames

Spaces removed from filenames.

**Comment by cbc02009** [comment]
Thanks for the changes. Can you add the type and length of screws used for the mod to the readme? other than that it should be good to go.

**Comment by aTinyShellScript** [comment]
Screw info has been added to the Readme in a 'BOM' section.

**Review by cbc02009 — APPROVED** [review]

**Pull request merged**
