### PR TITLE
Removing mods

### PR DESCRIPTION
**Pull request by thiagolocatelli**
I am removing the mods and moving to a new location.

Thank you.

### CODE REVIEW

**Comment by KiloQubit** [comment]
What licensing issues are you talking about?  Parts that were originally GPLv3 (all Voron parts) that have been modified are required to retain the GPLv3 license if they're distributed, they cannot be released under a different license.

**Comment by thiagolocatelli** [comment]
@KiloQubit  understood, but we can go ahead and remove them.

**Comment by KiloQubit** [comment]
I see that you have your mods in https://github.com/thiagolocatelli/Voron , but there's no license there.  As some of these are modified Voron parts, those mods that contain modified Voron parts must be licensed under GPLv3, as is stated in the license under which you received those Voron parts.  Therefore please add a copy of https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md to your mods that were modified from Voron parts.

Section 5.c
> You must license the entire work, as a whole, under this
License to anyone who comes into possession of a copy.  This
License will therefore apply, along with any applicable section 7
additional terms, to the whole of the work, and all its parts,
regardless of how they are packaged.  This License gives no
permission to license the work in any other way, but it does not
invalidate such permission if you have separately received it.

https://github.com/VoronDesign/VoronUsers/blob/master/LICENSE.md

**Comment by thiagolocatelli** [comment]
@KiloQubit my repo has been updated with the license you mentioned and updated a readme file to reflect that. Thank you sir.

**Comment by thiagolocatelli** [comment]
@KiloQubit links removed sir!

**Review by KiloQubit — APPROVED** [review]
Thanks for the update!

**Pull request merged**
