### PR TITLE
RockNRoll-Mod

### PR DESCRIPTION
**Pull request by RockNLol**
#### Which mods/configurations/profiles are added by this PR?
My RockNRoll-Mod, two rockers in the back of a V2.4 to roll the printer on its back for easy access to the electronics compartment.

#### How was it tested? 
I printed and assembled it. See pictures in my readme. One other discord user confirmed successful print and installation.

#### Any background context you want to provide?
My Voron V2.4 lives in a narrow closet sitting on a shelf higher than a table. Since its a 350mm build it is pretty heavy and moving it around to work on it was a pain. With this mod I can work on the electronics compartment without removing it from the closet first.

#### Further notes
It needs a tiny bit of support for aesthetic purposes. If I put the hex grid on the other side of the rocker, support wouldn't be needed, but it wouldn't look as good. The way it is now, it matches the style of the skirts nicely. If I have to change this, let me know.

Thanks in advance!

### CODE REVIEW

**Comment by cbc02009** [comment]
If supports are required they must be included in the STL. I would be okay with adding a supported and unsupported version though.

I think the bigger issue is that v2.4r2 is right around the corner, and it modifies the z assemblies in such a way that might make these incompatible. in order to save yourself some work it might be best to just hold off for now.

**Comment by RockNLol** [comment]
Alright, thanks for the feedback! I'll wait for V2.4r2 then.

**Comment by cbc02009** [comment]
v2.4r2 is out now. if you want you can either update the mod to be compatible with it, or just add a big bold warning to the readme saying it's only compatible with v2.4r1.

**Comment by RockNLol** [comment]
Hi,
thanks for the heads up. I already modified the CAD model to include minimal supports. I am planning to modify the r2's z drive base plate accordingly to ensure compatibility with r2.

**Comment by RockNLol** [comment]
I'm waiting on feedback from ✪Runanaツ#3906 on discord. They'll also try out the r2-feet support and provide me with photos.
The cavity between the two holes sagged during printing (was a 50mm bridge), thats why I added another support in the middle in [7131ac4]. Now it is a 25mm bridge, which should print fine.

**Comment by cbc02009** [comment]
please remove the file printer_mods/JosAr/Klicky-Probe/Usermods/Maverick/Images/Thumbs.db. After that everything should be good.

**Comment by RockNLol** [comment]
done! Should have set up my gitignore properly earlier.

**Pull request merged**
