### PR TITLE
The bad breath - Filtering system that anchor on top of the frame (voron 2.4 tested)

### PR DESCRIPTION
**Pull request by akhamar**
* [x] The mod, firmware configuration or slicer profile is in the correct category
    folder. Printable mods go to `printer_mods/`, firmware configurations
    go to `firmware_configurations/`, slicer profiles go to `slicer_profiles/`.
    Create a subfolder with your name, and place the mods in a subfolder with
    a descriptive name within that folder, e.g.: `/printer_mods/FHeilmann/flux_capacitor`
  * [x] Folder and file naming:
    * Folders and filenames shouldn't contain spaces. Only letters `a-zA-Z`, numbers `0-9`, underscores `_`, hyphens `-` and periods `.`
    * Primary color: `part_xyz.stl`
    * Accent color: `[a]_part_xyz.stl`
    * Opaque color (Blocks light): `[o]_part_xyz.stl`
    * Clear/transparent color (Allows light): `[c]_part_xyz.stl`
    * Quantity, if more than one is needed: `part_xyz_x4.stl`
  * [x] For each mod, add a small `README.md` file to its folder with a short description
    of what the mod accomplishes. This readme can be used to add pictures, give assembly
    instructions or specify a bill of materials if the mod requires additional hardware.
  * [x] The PR modifies the top-level `README.md` of the category folder adding the 
    contribution to the table. Read the top part of the file for instructions on how
    to do this. Please preserve the alphabetical ordering while adding new rows. Make sure
    to fill out the compatibility matrix to indicate which versions of the Voron printer
    the submission is compatible with.
  * [x] The mod/configuration/profile has been tested by the person submitting the mod 
    and/or other Voron users. Make sure to add information about how the mod was tested below. 
  * [x] The mod is not merely a slight modification of an official Voron part, configuration 
    or profile (i.e. an official Voron part with a few mm added or removed or a slicer profile 
    which only modifies a few values). *(When in doubt, contact one of the admins in the 
    Voron discord before submitting the PR)*
  * [x] Submitted STLs are printable without support. *(If the mod does not meet this criterion
    join the Voron discord and ask the other users for advice on how to modify the mod such 
    that it does not require supports)*
  * [x] Submitted STL files are not corrupt. *(This can be tested by opening the STL in PrusaSlicer
    and checking if mesh errors are reported.)*
  * [x] Submitted STL files are oriented and scaled properly for printing.
  * [ ] Submission includes a CAD file in the form of a `.STEP` or `.SCAD` file
  * [ ] Submitted firmware configs or slicer profiles contain no sensitive data (e.g. API keys).

#### Which mods/configurations/profiles are added by this PR?
The bad breath. This is a filtering system that anchor on top of the frame.
Please ignore all other folder as they come from an other pull req since about a month ago. The only part needed to be merge for this one is : **printer_mods\Mastah\the_bad_breath**

#### How was it tested?
On my printer. I replaced the nevermore by two of this.

#### Any background context you want to provide?
I printed nevermore V5, used it. Lid warped, air flow was "bad". Decided to do my own system.

#### Screenshots (if appropriate)
Images folder.

#### Further notes
Only merge and take care of the folder **printer_mods\Mastah\the_bad_breath** the other directories are since about a month in the pipeline of pull req.

### CODE REVIEW

**Review by MapleLeafMakers — COMMENTED** [review]
I'm not sure exactly what happened here, but you've got your breakbox mod in this PR as well (and it already has it's own PR here: https://github.com/VoronDesign/VoronUsers/pull/776) as well as 'mandalaRoseWorks_magnets_avoidance'

Aside from that there are a lot of filenames with spaces in them.  File and folder names should not contain any spaces.

**Comment by akhamar** [comment]
> I'm not sure exactly what happened here, but you've got your breakbox mod in this PR as well (and it already has it's own PR here: #776) as well as 'mandalaRoseWorks_magnets_avoidance'
> 
> Aside from that there are a lot of filenames with spaces in them. File and folder names should not contain any spaces.

Yep that's what I explained. I've already asked for a pull req for the other stuff but it's been already over a month and the branch for bad breath start from the master (which is the pull req for the other stuff). I wasn't expecting things to get this long on the PR hence I didn't started a branch earlier.

**Comment by akhamar** [comment]
> Aside from that there are a lot of filenames with spaces in them. File and folder names should not contain any spaces.

Only the folder `medium_body` had a space. Other files are ok.

And only the content of the folder `the_bad_breath` should be merge.

**Comment by MapleLeafMakers** [comment]
> And only the content of the folder `the_bad_breath` should be merge.

We dont get to pick and choose what gets merged from a PR, it's all-or-nothing.  this needs to be cleaned up before it can be looked at.

**Comment by akhamar** [comment]
> > And only the content of the folder `the_bad_breath` should be merge.
> 
> We dont get to pick and choose what gets merged from a PR, it's all-or-nothing. this needs to be cleaned up before it can be looked at.

Ok. I can either wait for the first PR to be merge or delete everythinbg else and manage on my side when i'll merge the branch into my main.
It depends on how long it usually take to merge a PR. My first is already about a month old.

**Comment by MapleLeafMakers** [comment]
Unfortunately, we don't have many people that have the knowledge to review a PCB, and there are a TON of files in that one to go through.  I don't think I can offer any kind of time-frame for you on that one.  it may take a while.

**Comment by akhamar** [comment]
> Unfortunately, we don't have many people that have the knowledge to review a PCB, and there are a TON of files in that one to go through. I don't think I can offer any kind of time-frame for you on that one. it may take a while.

Ok I didn't think It was gona take this much time.
I might just create a new repo and create a branch for each mods.

**Pull request closed without merging**
